### ISSUE TITLE
[Request] REST API to invoke OctoPrint system commands

### ISSUE THREAD

**Issue by mcecchi** [foosel/OctoPrint#1619] opened 2016-12-03 08:26 UTC
Hi,

I'm developing an Android App for controlling 3D printer via OctoPrint REST API.

I think would be very useful a REST API for execute SYSTEM commands defined in OctoPrint.

Thanks for your amazing job!

MC

**Comment by Salandora** [comment] 2016-12-03 09:17
Hello @mcecchi

this is already possible.

Here a link to the devel branch documentation
http://docs.octoprint.org/en/devel/api/system.html#execute-a-registered-system-command

This was also possible in master but I can't find it in the documentation so here a link to the python code.
https://github.com/foosel/OctoPrint/blob/master/src/octoprint/server/api/__init__.py

Hope it'll help you.

**Comment by foosel** [comment] 2017-01-27 18:01
Duplicate of #804 and as already pointed out also finally documented, now even on master: http://docs.octoprint.org/en/master/api/system.html

**Closed by foosel** 2017-01-27 18:01 UTC
Labels: type:request
