### ISSUE TITLE
Pause and subsequent cancel causes UI to become unresponsive.

### ISSUE THREAD

**Issue by ralxnder** [foosel/OctoPrint#2587] opened 2018-04-16 14:50 UTC
#### What were you doing?
Pausing and then canceling print

1. Pause current print
2. Cancel current print without resuming
3. ...

#### What did you expect to happen?
I expect the print job to be cancelled successfully and the UI to go back to a ready state.
#### What happened instead?
The UI hangs in a "Cancelling" state and is unresponsive unless I disconnect and reconnect. I cannot control my print with any of the buttons as they are all grayed out.
#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
Octoprint 1.3.8

#### Operating System running OctoPrint
OctoPi 0.14.0

#### Printer model & used firmware incl. version
Anet A8 running a MKS Gen 1.4 board loaded with Marlin 1.1.8.

#### Browser and version of browser, operating system running browser
Chrome Version 65.0.3325.181 (64-bit) running on Windows 10 Pro

#### Link to octoprint.log
[octoprint.log](https://github.com/foosel/OctoPrint/files/1915775/octoprint.log)

#### Link to contents of terminal tab or serial.log
[serial.log](https://github.com/foosel/OctoPrint/files/1915777/serial.log)

#### Screenshot(s)/video(s) showing the problem:
![2018-04-16 10_25_52-clipboard](https://user-images.githubusercontent.com/6548415/38814873-9647cf6c-4160-11e8-9f41-2347a0f4b35e.png)

I have read the FAQ.

**Comment by foosel** [comment] 2018-04-16 17:28
Please *enable* `serial.log` (Settings > Serial Connection > Enable `serial.log`), then reproduce the issue, then post the resulting log.

**Comment by Serray** [comment] 2018-04-17 04:56
I had the same issue with pausing my print.
I clicked on pause print, normally it should perform the custom GCODE which i added to the pause button,
which should raise the head from the object.
The status of the printer didnt change from printing to paused.
I wasnt able to send any commands to the printer.
Also for me, all buttons were grayed out

Ruined my 7hrs print.

**Comment by foosel** [comment] 2018-04-17 06:29
@Serray for you the same goes as for @ralxnder. I need logs. I can't reproduce this myself. *I depend on logs to be able to debug this*.

**Comment by ralxnder** [comment] 2018-04-17 12:14
Here is a serial.log. I was seeing the same as @Serray, buttons are grayed out.

[serial.log](https://github.com/foosel/OctoPrint/files/1919587/serial.log)

**Comment by flashmani** [comment] 2018-04-17 14:10
I also faced the same issue. To rework we have restart the octoprint. This issue is happening after the latest update.

**Comment by NeroBurner** [comment] 2018-04-17 22:10
I found a workaround until the issue is resolved. When the pauseing gets stuck and the buttons are greyed out, then go to `Terminal` > `Advanced Options` > `Fake Acknowledgement`. Then the print status should be `Paused`

Related: https://github.com/foosel/OctoPrint/issues/2581

**Comment by foosel** [comment] 2018-04-18 12:37
Found and fixed by the above commit. Both this and #2581 had the same race condition as root cause. Until 1.3.9 is released (currently traveling, so can't look into this due to lack of a proper test environment) hitting "Fake Acknowledgement" as described above is a functioning work around.

**Comment by foosel** [comment] 2018-04-25 14:36
Just to make this easier to find... 

[**Workaround for this issue can be found here**](https://discourse.octoprint.org/t/octoprint-wont-cancel-after-1-3-7-update/1176/31?u=foosel)

**Comment by foosel** [comment] 2018-06-25 13:27
@DrWatson I doubt it. But it's hard to say without `octoprint.log` and `serial.log` and your settings ;)

**Comment by DrWatson** [comment] 2018-06-25 13:31
Thanks for the response. I think I am going to upgrade to 1.3.9rc1 and see if the problem goes away so at least I'm on the most recent code stream.

**Closed** 2018-07-25 14:46 UTC
Labels: status:solved, type:confirmed bug
