### ISSUE TITLE
M303 PID Autotune with Marlin crashes Octoprint

### ISSUE THREAD

**Issue by JosvdP** [foosel/OctoPrint#530] opened 2014-08-03 20:02 UTC
1. What were you doing?
Autotune PID to my Printrboard running Up-Marlin V1 firmware by sending command M303S200C10.

2. What did you expect to happen?
Autotune to run and finish. See the temperature plots going up and down.

3. What happened instead?
I can see the PID autotune starting and the temperature going up for a few seconds, then the communication between Octoprint and the Printrboard just stops. Octoprint doesn't crash as I can still do everthing, it just doesn't seem to communicate with the Printrboard anymore.
I get no temperature readings and nothing is happening in the Terminal anymore. Manual control and setting a target temperature works fine before I send any M303 command.

4. Branch & Commit or Version:
Not sure what branch I got, my Octoprint doesn't show the version information in the lower left corner of the GUI. It's a master branch downloaded today though.
I'm on Windows 7
I installed Octoprint as per instructions from the wiki. https://github.com/foosel/OctoPrint/wiki/Setup-on-Windows

5. Link to octoprint.log on gist.github.com or pastebin.com:
http://pastebin.com/e9b8XHNM
I'm afraid the whole log didn't make it because I don't know how to shutdown Octoprint nicely. I just hit CTRL-X in my command prompt window.

6. Link to contents of terminal tab on gist.github.com or pastebin.com:
http://pastebin.com/Xq97nrM4

Oh and I love cookies!

**Comment by foosel** [comment] 2015-03-23 12:25
Since I still can't reproduce this and OP doesn't have time for diagnostics, closing this for now.

**Closed by foosel** 2015-03-23 12:25 UTC
Labels: status:unreproduced
