### ISSUE TITLE
[Request] Add manual Start/Stop Recording to the Timelapse

### ISSUE THREAD

**Issue by demtat** [foosel/OctoPrint#1886] opened 2017-04-25 22:46 UTC
It would be very handy if you added manual Start/Stop Recording functionality to the Timelapse area.  I occasionally would like to record a Timelapse of a project that I happened to have printed from the SD Card using the printer's control panel.

**Comment by foosel** [comment] 2017-05-04 16:10
This is actually a duplicate of #452

**Closed by foosel** 2017-05-04 16:10 UTC
Labels: type:request
