### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by rosterloh** [foosel/OctoPrint#2675] opened 2018-06-06 09:31 UTC
#### What were you doing?

Loading a print from the SD card which was sliced for the Prusa MK2S with Simplify3D

#### What did you expect to happen?
Octoprint to continue functioning

#### What happened instead?

Serial connection the the printer disconnected

#### Version of OctoPrint
OctoPrint 1.3.8

#### Operating System running OctoPrint
OctoPi 0.15.1

#### Printer model & used firmware incl. version
Prusa i3 MK2S firmware 3.1.0

#### Link to octoprint.log

https://gist.github.com/rosterloh/d62c612de0239ab92a79a6e908961b24

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment] 2018-06-06 10:05
You description of what you were doing when this happened (printing from SD) doesn't match what I see in the log (sending a file to SD). So which one was it?

**Comment by foosel** [comment] 2018-06-06 10:10
Oh, and as a side note:

> **Printer model & used firmware incl. version**
> Prusa i3 MK2S firmware 3.1.0

[That firmware has serious communication issues and should therefore not be used with any kind of host program (incl. OctoPrint)](https://discourse.octoprint.org/t/printer-specific-original-prusa/239#headline--communication-issues-3.1.0).

**Comment by rosterloh** [comment] 2018-06-07 08:01
It seems to be working now. The error just asked me to submit it so trying to be a good citizen. Thanks for the tip about the firmware.

**Comment by foosel** [comment] 2018-06-09 10:46
And it was good that you reported it. I'm still not sure how that got triggered in the first place (based on what I saw in the code that could only ever possibly caused by trying to stream a file to the printer that's either empty or only consists of comments that will be stripped), but it shouldn't be possible to trigger it in the future.

Fix is pushed to `maintenance`, soon `devel`, to be released with 1.3.9

**Closed** 2018-07-25 14:46 UTC
Labels: status:solved, type:confirmed bug
