### ISSUE TITLE
skipped steps upon reload of website

### ISSUE THREAD

**Issue by universam1** [foosel/OctoPrint#2777] opened 2018-08-02 19:02 UTC
#### What were you doing?

When I reload the website of OP this reproducible causes steps or layers to be skipped. The same happens when I open the website from another device like a smartphone. When the page has been loaded before, the print is fine.
After upgrading of OP this issue started to raise.
Happens probably since version >1.3.5, I can reproduce the issue with 1.3.8 and update on 1.3.9 does not solve it.
The issue has not been on OP versions older than 1.3.6 as far as I remember, though hard for me to downgrade for tests.
Tried different Marlin FW versions for doubt, but has no influence. Tested with 1.1.8, bugfix and 1.1.9
Printing for years on this setup, Prusa i3 with OP running on OrangePi w/ 1GB RAM with CPU usage of <20% and RAM is mostly free

#### What did you expect to happen?
Reload of webpage should not cause print to skip steps
#### What happened instead?
skips steps
#### Did the same happen when running OctoPrint in safe mode?
uninstalled all plugins

#### Version of OctoPrint

1.3.9 and 1.3.8

#### Operating System running OctoPrint
Armbian on OrangePi
CPU load is under 20% all the time

No Serial errors logged during the failure

#### Printer model & used firmware incl. version
Prusa i3
Marlin FW 1.1.9
#### Browser and version of browser, operating system running browser
Chrome on W10
Chrome on IOS
#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/10851289/43604931-434fd7c8-9697-11e8-912b-0e8bb92acf6a.png)

I have read the FAQ.

**Comment by ntoff** [comment] 2018-08-02 22:26
https://github.com/foosel/OctoPrint/issues/1241 Probably a duplicate of this

**Comment by foosel** [comment] 2018-08-20 09:28
I agree with @ntoff, sounds like a duplicate.

**Closed by foosel** 2018-08-20 09:28 UTC
Labels: type:potential bug
