### ISSUE TITLE
[Request] Chat function on Controls Page

### ISSUE THREAD

**Issue by joeydraft** [foosel/OctoPrint#2079] opened 2017-08-14 19:50 UTC
I think it would be cool to have a chat function on the 'Controls' tab. 

Simple text box and submit button, goes line by line, then archives with the print name, and time of comment.
So you can make comments as the print goes. 
Or multiple people can comment on the same print if watching together. I have a few friends that check in on my prints as they are going, so it would be fun for them to make comments for me to see.

Love OctoPrint btw!
Prusa i3 mk2s - Pi3

Thanks!
Joey

**Comment by foosel** [comment] 2017-08-21 12:25
I'd say this is actually a duplicate of #519

**Closed by foosel** 2017-08-21 12:25 UTC
Labels: plugin-only, type:request
