### ISSUE TITLE
[Request] More dynamic administration/access control.

### ISSUE THREAD

**Issue by DylanB00** [foosel/OctoPrint#1332] opened 2016-05-13 06:03 UTC
I'm currently setting a 3D Printer up with the server at my school. Something that we feel OctoPrint lacks is a true access control. We would like to have it where you must gain permission to print/pause/cancel a job (via a password entry on webpage) for a standard user (which would probably be a student using it). Currently, anyone who we add as a user can interrupt anyone else's builds and put in their own, or even go 'nihilistic' on the 3D Printers and not use them for their actual purpose. We see this as an issue because some students would be willing to do this, so adding more dynamic administration options (who logged in last, specific privilege configurations, etc) would really help in the program not only for school use but also for business use.

**Comment by markwal** [comment] 2016-05-13 22:30
Duplicate of #1110

**Closed by markwal** 2016-05-13 22:30 UTC
Labels: type:request
