### ISSUE TITLE
[Request] Continued printing from the interrupted place

### ISSUE THREAD

**Issue by userosos** [foosel/OctoPrint#1835] opened 2017-03-25 16:26 UTC
Hello everyone! I want сontinuation printing from interrupt place if my print was interrupt i can set parameters (number line in file of g-code (it need do like number line and Axle height Z in mm ), temperature and other) and go print from number line in g-code. I think it will very good.

**Comment by foosel** [comment] 2017-03-27 14:52
Duplicate of #112

**Closed by foosel** 2017-03-27 14:52 UTC
Labels: type:request
