### ISSUE TITLE
continue on communication error

### ISSUE THREAD

**Issue by splitbrain** [foosel/OctoPrint#27] opened 2013-01-20 13:02 UTC
I just had a print stop because OctoPrint lost connection with the printer for some reason:

```
Communication timeout during printing, forcing a line
```

Disconnecting and reconnecting fixed the error and OctoPrint continued to correctly show the temperatures. However, clicking the "print" button did reset the whole print job making it start from scratch instead of continuing where it left off. Would be nice if it could have simply continued. Maybe even doing the disconnect/connect thing itself after having a timeout for multiple times in a row.

**Comment by guysoft** [comment] 2015-02-23 23:53
I just got this issue too. Only happens on large gcode files. Its consistent. Is there a way to debug this?

**Comment by jeremyferris** [comment] 2015-05-13 22:19
Hello Everyone.

I have been experiencing this issue for a while now, and every time it happens, it seems to be a power issue with the PI. I have experienced weird things with the PI related to power with various different applications (XBMC, OctoPi, running Raspbian).

The problem started again the other day, and although I was connected to an ATX power supply, the micro-usb connector I was using could not handle the power load. I switched cables and went to a 1A wall adapter, but the problem continued. I am now using a LiPo battery pack that can deliver a nice clean 2.5A and the problems have disappeared.

I suspect that the Pi's USB chip cannot handle power fluctuations.

Bottom line is: If you are experiencing problems, check your cabling and power to the Pi. Many of the micro-usb cables out there are very poor quality, so get one that is good. Many of the wall adapters out there are very noisy and are intended solely for charging phones, not running things that are susceptible to noisy power like the Pi.

@guysoft I am not sure on the size issue, but if nothing else in your setup has changed, try re-seating the Pi's power connection to see if it resolves the problem. Alternatively, solder on a more permanent connection for power to the Pi. I am currently printing a 7MB file that had hundreds of pauses (communication timeouts) yesterday, but after my fix today, not a single pause (timeout).

- Jeremy

**Comment by Brianp82** [comment] 2016-11-04 04:26
I am having this issue . So what it the best say to permanently power the pi?

**Comment by ctgreybeard** [comment] 2016-11-04 04:34
If the red light is not on steady or not on at all then you have low power. This causes the Pi to slow down. Get a good 5.25 volt, 2.5 amp wall wart.

**Comment by Brianp82** [comment] 2016-11-04 04:44
Hey, I have a 2.5a wall wart that came with my pi purchase. The red light is solid on. There is a link to the pi I bought and you can see the wall power adapter. What do you think?

https://www.amazon.com/gp/product/B01C6EQNNK/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1

**Comment by ctgreybeard** [comment] 2016-11-04 04:48
For the Pi3 at least, If the red light is on solid then your power is good.

**Comment by Brianp82** [comment] 2016-11-04 05:00
Any other suggestions then to get rid of communication timeouts while printing?

**Comment by jeremyferris** [comment] 2016-11-04 05:22
For me, it ended up being the micro-usb cable powering the Pi. Make sure you have a good quality one or consider powering it from the gpio header. I now power mine with the atd power supply i am using to power my printer.

Also make sure you have a good quality usb cable to the printer. It sees a lot of vibration on some printers.

Work-arounds:
- put jobs on an sd card and run it from there 
- consider using a dielectric grease on the micro-usb connections, might help

- jeremy

**Comment by jeremyferris** [comment] 2016-11-04 05:23
Atd power supply = atx power supply

**Comment by Brianp82** [comment] 2016-11-04 05:27
Well like I think I mentioned, I'm using a micro usb to power the pi . But it's he 2.5a wall adapter included in the pi combo kit. It's made for it and low noise it says. The usb cable from the pi to printer is the one that came with my printer. And I have printed tons of prints with it. Until I used octoprint with the pi.

**Comment by nophead** [comment] 2016-11-04 08:55
I have to set the communication timeout to 200s otherwise it times out on objects with a large first layer. When the infill lines are the full diagonal length of the bed and the first layer is printed slowly a buffer full of them takes minutes, not 20s. I printed for years with a smaller timeout before I ran into this problem.

Of course 200s is no good if you actually have a comms error as you would get a massive blob, but I never get comms errors with an RPI connected to a Melzi, both powered by the same ATX.

**Comment by Brianp82** [comment] 2016-11-04 09:19
Thanks for the info nophead.  When I checked my terminal tab it just had a gcode command Yat was sent like normal but then it froze  and a few seconds later it said the the communication timeout message and basically ended up restarting itself because it never picked back up in time .  Mine doesn't happen on any specific print or at least that I can tell.  So I have my raspi connected right to my printer via USB.  Does anyone have a picture of them powering their printer and pi off a atx psu? Mine is just plugged into the wall

**Comment by nophead** [comment] 2016-11-04 09:56
I use the purple 5V standby wire and either splice it to a micro USB plug or connect it to the 5V pin on the GPIO (note this bypasses the fuse). Ground can come from any of the black wires or ground on the controller for less USB noise.

I then turn the ATX on and off via the green wire by connecting it to a GPIO pin with a small MOSFET.

**Comment by foosel** [comment] 2017-01-27 12:47
Timeout durations can be configured, continuous timeouts on anything other than long running commands or long/slow moves hint at communication issues that should otherwise be tackled (and as mentioned they can be caused by power supply issues on something like a Pi), and just blindly continuing on repeated timeouts is possible too by setting the allowed consecutive timeouts to 0 (= don't care), even though that might lead to huge print issues if there is indeed a communication issue on the line and is hence not implemented by default.

On top of things the whole communication layer has been pretty much revamped compared to when this ticket was created four years ago.

Therefore: Closing this.

**Closed by foosel** 2017-01-27 12:47 UTC
Labels: type:request
