### ISSUE TITLE
[Request] Add unauthenticated user to Access Control

### ISSUE THREAD

**Issue by overkillthemighty** [foosel/OctoPrint#2665] opened 2018-05-24 17:53 UTC
I was looking at what was available to an unauthenticated user and thought it would be nice to be able to turn elements on or off (For example the ability to see/download prints, or the ability to see the web stream). It seems these features could be used to cause issues by overloading a system that is printing (especially a low powered system). Adding a user to access control with a few checkboxes seems like a good way to accomplish this. Thanks for your amazing work!

**Comment by foosel** [comment] 2018-05-25 06:45
Duplicate of #1110 which is already implemented on `devel` and to be released with 1.4.0 (still a while off).

**Closed by foosel** 2018-05-25 06:45 UTC
Labels: type:request
