### ISSUE TITLE
[Request] "click to resume" Marlin 1.1.8

### ISSUE THREAD

**Issue by flmcampos** [foosel/OctoPrint#3136] opened 2019-05-02 14:07 UTC
I have a program on a Rasp Pi that connects to a printer and automatically sends M114 and M105 for monitoring the printer. When I run a print from the SD card the printer after reaching the setpoints Temperatures, it just stops and the LCD shows a "click to resume" message. After I click it works fine on most of the times but sometimes the message appears again.

Is there something that can be done for the printer just run normally without any pause between a print and sending these Gcodes?

**Comment by foosel** [comment] 2019-05-02 17:51
Duplicate of https://community.octoprint.org/t/click-to-resume-marlin-1-1-8/9317

**Closed by foosel** 2019-05-02 17:51 UTC
Labels: type:request
