### ISSUE TITLE
Can't close notification dialog on raspberry

### ISSUE THREAD

**Issue by WolfgangFahl** [foosel/OctoPrint#3076] opened 2019-03-08 10:44 UTC
#### What were you doing?
Trying to use octoprint in a browser directly on a raspberry Touch which also runs the server.

#### What did you expect to happen?
Being able to use the controls
#### What happened instead?
A notification dialog hides the controls. The button to close the notification dialog is not visible and not reachable via scrolling.
#### Did the same happen when running OctoPrint in safe mode?
N.A.

#### Version of OctoPrint
1.3.10

#### Operating System running OctoPrint
raspbian

#### Printer model & used firmware incl. version
N.A.

#### Browser and version of browser, operating system running browser
default raspbian browser
#### Link to octoprint.log
N.A.

#### Link to contents of terminal tab or serial.log
N.A.

#### Link to contents of Javascript console in the browser
N.A.

#### Screenshot(s)/video(s) showing the problem:

![grafik](https://user-images.githubusercontent.com/1336221/54024145-2cdc1a00-4197-11e9-9d7e-eafa83a9535f.png)

I have read the FAQ.

**Comment by WolfgangFahl** [comment] 2019-03-08 10:49
I worked around the issue by zooming the screen to 25%

**Comment by foosel** [comment] 2019-03-08 11:07
Duplicate of #2959 and already fixed on `maintenance`, fix will be released with 1.3.11 ,)

**Closed by foosel** 2019-03-08 11:07 UTC
Labels: type:potential bug

**Comment by foosel** [comment] 2019-03-08 11:10
As a side note, I'd really not recommend to use the same Raspy that you use for driving your printer (and running OctoPrint) to also run a full fledged desktop environment on and a browser displaying the UI in it.

OctoPrint was designed to do as much as possible on the client to remove load from the server which usually is a low powered single board computer. If you run the UI on the very same device you can overload it and negatively influence your print jobs.

**Comment by WolfgangFahl** [comment] 2019-03-08 11:42
This was not for the print job itself but for the calibration tasks in advance of it. Having a touch screen right beside the printer is really handy for this. Would it be possible to separate just the control part of the ui to a less load demanding version?

**Comment by foosel** [comment] 2019-03-08 11:44
Sure, if someone writes it :) All the needed bits are there, API, plugin hooks, docs, everything.
