### ISSUE TITLE
[Request] Show CPU usage

### ISSUE THREAD

**Issue by Lord2Vader** [foosel/OctoPrint#1143] opened 2015-12-13 18:41 UTC
Hi,

due to some problems with browser on the pi (on TFT-Touchscreen or so) the CPU usage should be shown. If possible per core :)

**Comment by foosel** [comment] 2015-12-13 19:13
OctoPrint is platform agnostic, therefore that's something that should be done in a plugin.

**Comment by myersCody** [comment] 2016-02-24 16:23
My undergrad team and I would like to resolve this issue through a plugin, if no one is currently assigned to the task.
Thanks,
Cody Myers & Angela Reinhard

**Comment by foosel** [comment] 2016-02-24 16:57
Don't know of anyone, so marking as grabbed by you, thanks!

**Comment by foosel** [comment] 2017-01-27 15:23
Actually a duplicate of #814

**Closed by foosel** 2017-01-27 15:23 UTC
Labels: plugin-only, type:request, up-for-grabs
