### ISSUE TITLE
[devel] Unable to load UI - seems related to tornado

### ISSUE THREAD

**Issue by gege2b** [foosel/OctoPrint#2949] opened 2018-12-12 11:32 UTC
#### What were you doing?

Upgraded from OctoPrint 1.4.0.dev1455+gf72f9487 to 17ad63dabf90da8beb2b01f7fdf7c93681f54c81
I saw a bunch of errors in the upgrade dialog and was worried, but in fine, he said "upgrade successfull"

But as soon as I want to access the UI, I only get the spinning wheel and nothing else.
What I discovered be accessing the log from SSH is that Tornado is raising a continous number of error  as long as the browser tab stays open (my octoprint.log is ~ 2GB right now)

#### What did you expect to happen?
Smooth upgrade and usability

#### What happened instead?
A mostly dead brick :) 

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

1.4.0.dev1455+gf72f9487

#### Operating System running OctoPrint

Raspbian stable

#### Printer model & used firmware incl. version

prusa mendel with marlin 1.1.8

#### Browser and version of browser, operating system running browser

Firefox 63 on windows 10 and Kubuntu (same problem)

#### Link to octoprint.log
Octoprint and software update log below

[It's zipped but pretty big](https://framadrop.org/r/ECHRm578n3#LinnlW2rMkqAMdVat+NxC3PEVA39ZBBiXCbFFmUawgo=) (33MB ziped)
Please note : link will be available for 30 days only

#### Link to contents of terminal tab or serial.log
not applicable

#### Link to contents of Javascript console in the browser

```
Starting dependency resolution... packed_core.js:16029:9
... dependency resolution done packed_core.js:16139:9
Initial application setup done, connecting to server... packed_core.js:16441:9
SecurityError: Permission denied to access property "_jp" on cross-origin object htmlfile:8
Échec du chargement pour l’élément <script> dont la source est « http://prusa.home:5000/sockjs/991/21zceg0n/jsonp?c=_jp.ac2gnnv ». prusa.home:5000:1:1
SecurityError: Permission denied to access property "_jp" on cross-origin object htmlfile:8
Échec du chargement pour l’élément <script> dont la source est « http://prusa.home:5000/sockjs/987/jeypuihb/jsonp?c=_jp.adrvsgc ». prusa.home:5000:1:1
SecurityError: Permission denied to access property "_jp" on cross-origin object htmlfile:8
Échec du chargement pour l’élément <script> dont la source est « http://prusa.home:5000/sockjs/151/11uzawzo/jsonp?c=_jp.aol0ird ». prusa.home:5000:1:1
SecurityError: Permission denied to access property "_jp" on cross-origin object htmlfile:8
Échec du chargement pour l’élément <script> dont la source est « http://prusa.home:5000/sockjs/675/25gckjaz/jsonp?c=_jp.a4md2en ».
```
And it keeps looping...

#### Screenshot(s)/video(s) showing the problem:

There is only the spinning wheel shown when loading the UI, that's all
![image](https://user-images.githubusercontent.com/2814966/49867425-c7cc8e80-fe0a-11e8-9523-055f0153fd7d.png)

I have read the FAQ.

**Comment by foosel** [comment] 2018-12-12 11:48
The `devel` branch currently has some issues it seems after merging it with 1.3.10. I'll take a look as soon as possible, until then I suggest to not run it or revert to an earlier commit.

It's a development branch after all ;)

**Comment by foosel** [comment] 2018-12-12 12:58
Ah. Duplicate of #2944

**Closed by foosel** 2018-12-12 12:58 UTC
Labels: type:potential bug
