### ISSUE TITLE
[Request] Multiple Camera Support

### ISSUE THREAD

**Issue by joeydraft** [foosel/OctoPrint#2099] opened 2017-08-28 15:45 UTC
Hello!

I would love to see multiple camera support within OctoPrint. 
I have a Pi Camera V2 attached to the print bed, but I would also like to have a second camera further out to see more of the full printer. It would be awesome to see both video feeds from the Control tab. 
More than 2 would even be better!

Thanks!
Joey

**Comment by foosel** [comment] 2017-08-28 15:49
Duplicate of #401 :)

**Closed by foosel** 2017-08-28 15:49 UTC
