### ISSUE TITLE
Gcode viewer out of the window

### ISSUE THREAD

**Issue by RFranta** [foosel/OctoPrint#719] opened 2015-01-14 08:39 UTC
When I go to gcode viewer tab I dont see the gcode platform. I found that is somewhere out of the window and if I press the left mouse button and drag down I can finally see ithe platform, but next time when I restart my device I dont see gcode viewer again. Can I set the position of gcode platform to be lower on start?

I am using Olinuxino A20 (similar to RPi) and browsers Midori and Google Chrome.
I tried version OctoPrint 1.1.1-4-gc35b7a6-dirty (master branch)
2014-06-13 and also today I updated to newest version by "git pull && python setup.py install"
Firmware is Marlin about 6 months old version with megatronics board, but because I don't see gcode viewer even without connecting, problably doesn't matter.

Here are my log files

Octoprint log:
http://pastebin.com/8nTzGxEG

I love cookies

Octoprint terminal:
http://pastebin.com/2Yce22PX

**Comment by foosel** [comment] 2015-01-14 09:39
Your working copy is dirty according to the version string. Please make sure that this issue is not caused by any changes you made to the code.

Also check your browser's error console.

**Comment by RFranta** [comment] 2015-01-14 10:59
Here is the log from the updated Octoprint (it's not dirty now):
http://pastebin.com/6vhWjxDs

But problem still remain.

Here is console log:
http://pastebin.com/rDG5HhmM

There is error "Failed to load resource: the server responded with a status of 404 (NOT FOUND) http://192.168.1.103:5000/static/js/lib/jquery/jquery.min.map"
Could that be the problem?

**Comment by foosel** [comment] 2015-01-15 15:43
And github also didn't notify me of this reply. Grmpf :/

Ok. That jquery error is not the reason here. You are seeing the same behaviour in both midori and chrome?

How are your Renderer Options set beneath the viewer? This should be the default:

![image](https://cloud.githubusercontent.com/assets/83657/5760529/94614882-9cd5-11e4-9d86-c47e0173741e.png)

**Comment by RFranta** [comment] 2015-01-15 15:55
Yes, I have default Renderer options same as on you rscreenshot and yes,
it look the same both on Chrome, Firefox and Midori.

**Comment by foosel** [comment] 2015-01-15 16:03
Is this with or without a loaded file? If with a loaded file, can you supply the file? If without, can you try with one?

**Comment by RFranta** [comment] 2015-01-15 16:40
Its both with and without, but any file is loaded properly in gcode viewer so that shouldnt be the case.

**Comment by foosel** [comment] 2015-01-15 16:46
As said in the other ticket of you, I'm at a complete loss regarding this too. Nothing in the javascript console, can't be caused by a loaded file either, no weird options. I'm out of ideas and I fear I'll have to capitulate for now, sorry

**Comment by RFranta** [comment] 2015-01-15 16:50
Only different think is that I am using Olinuxino, not RPi. 

Is there any variable in Octoprint code that would move the platform on start in Y axis? I know its not a nice solution but it would help me. Thanks

**Comment by nophead** [comment] 2015-01-15 16:53
Actually I have seen the grid appear not in the centre of the window sometimes. I just drag it to where is should be.

**Comment by irrenhaus** [comment] 2015-01-17 15:54
I can confirm this too, only experienced it after using a fresh installation of OctoPi (like around 15 days ago). I think it was running version 1.1.1 (not exactly sure, I'm currently not using it). Checking the "Center viewport on model" checkbox fixed it each time.

If there's anything I can check let me know, I will then try to reproduce it.

**Comment by Arengorn** [comment] 2015-01-18 19:05
I can also confirm this. It used to happen every single time I uploaded and loaded a Gcode, but ever since I moved to devel (**1.2.0-dev-395-g4e4ad0b**) this has been much less recurring. At times if the Gcode file was very large, above 20Mb or so, the grid would be out of the window and it would 'stick' to the mouse making it impossible to center. Neither 'center viewport on model' nor 'zoom in on model' options would help in that, or in any case.

**Comment by foosel** [comment] 2015-01-19 12:31
I just managed to successfully reproduce this (or at least something that looks suspiciously like it) on `master`. That's at least a start I guess.

**Comment by foosel** [comment] 2015-01-19 15:28
I just pushed a change to **``master``**, can everyone affected by this please check if that solves the issue for you? If not, please provide a screenshot.

**Comment by RFranta** [comment] 2015-01-19 17:09
Now it's bed centered great! Works nice both on Olinuxino LCD display in Midori and in my PC in Chrome. Awesome. Thank you very much!

**Comment by foosel** [comment] 2015-01-22 09:45
@Arengorn @nophead @irrenhaus Can you give it another test too?

**Comment by nophead** [comment] 2015-01-22 10:46
That is worse for me because the model is no longer in the centre of the grid, presumably because my origin is 0,0, not 100,100. Previously the model was centred on the grid but the grid was not always centred. That was easy to fix by dragging it.

**Comment by irrenhaus** [comment] 2015-01-22 10:54
I will have a look this evening or tomorrow, whenever I find time for it.

**Comment by foosel** [comment] 2015-01-22 11:00
@nophead Ah, so now you are running into what @imitation described in #677 and which is tracked in #682. I guess this bug somehow covered this up for you. I'll try to look into it, on the `master` branch you still should be able to work around it by setting an offset for the extruder 1 though like described in #677 

@irrenhaus thanks!

**Comment by nophead** [comment] 2015-01-22 11:33
Yes adding an extruder offset puts it back in the centre of the grid. Does
that have any other side effect?

**Comment by foosel** [comment] 2015-01-23 12:16
Only if you run multi extruder setups. It might have some small effect on how the gcode interpreter analyses your files, but that shouldn't really affect your. So I guess not.

**Comment by irrenhaus** [comment] 2015-01-23 17:16
@foosel Fixed for me :) Thank you very much!

**Comment by foosel** [comment] 2015-01-23 17:18
Ok, closing this then. 

@nophead I hope you can live with the offset workaround for a while until I implement #682

**Closed by foosel** 2015-01-23 17:18 UTC
Labels: status:accepted

**Comment by nophead** [comment] 2015-01-24 11:51
Yes it is working fine for me and since updating the gcode viewer always
seems to work. Previously it only worked occasionally.

Regarding the first extruder offset. I think it always needs a configurable
setting because some deltas have three nozzle arranged radially, so they
are all offset relative to the centre of the end effector.
