### ISSUE TITLE
[Request] add speed & flow multiply option

### ISSUE THREAD

**Issue by MLWORKX** [foosel/OctoPrint#777] opened 2015-02-20 21:18 UTC
- Sometimes it would be really helpfull to have a speed & flow multiply option as you have on RepetierHost (see picture).
- as I have a dual head printer it would be nice to have a seperate flow multiply for extruder 0 and 1

(currently using 1.2.0-dev-480-geb4156c (devel branch))

![octo](https://cloud.githubusercontent.com/assets/4218023/6309480/26f2f7ce-b94e-11e4-9b1a-0ae302797dac.png)

**Comment by fotis400** [comment] 2015-02-21 00:47
You can have this functionality by setting up some custom buttons.

Place in your config.yaml file the following:

```
controls:
- children:
  - command: M220 S%(percent)s
    input:
    - default: 100
      name: "Speed factor (%)"
      parameter: percent
    name: Set
    type: parametric_command
  - command: M221 S%(percent)s
    input:
    - default: 100
      name: "Extrude factor (%)"
      parameter: percent
    name: Set
    type: parametric_command
  name: Speed & Flow overrides
  type: section
```

**Comment by MLWORKX** [comment] 2015-02-21 09:01
That will work, thank you very much!
...but I think this should be more a "standard" feature which belongs into the "control" tab

**Comment by foosel** [comment] 2015-02-22 15:49
[x] you have not used the search function

Duplicate of #362

**Closed by foosel** 2015-02-22 15:49 UTC
