### ISSUE TITLE
/plugin/appkeys/decision/<str:user_token> returns 404

### ISSUE THREAD

**Issue by dkulinski** [foosel/OctoPrint#3257] opened 2019-08-27 03:58 UTC
#### What were you doing?
When trying to generate an application key using the appkeys plugin I am unable to properly authorize the application.

When trying to reproduce:
1. Generate an appkeys request
2. Hit approve or deny in the OctoPrint UI
3. Check the octoprint.log and a tornado.access warning will be present:

```
2019-08-27 03:37:23,528 - tornado.access - WARNING - 404 POST /plugin/appkeys/decision/12d09298e5c7019d15a054fd1bdd26db (::ffff:192.168.NNN.NNN) 35.42ms
```
4. The requesting process is always returned a 202 status code

#### What did you expect to happen?
After a decision is made the endpoint should return either a 404 or a 200 with the key

#### What happened instead?
The end point never returns anything but a 202 status

#### Did the same happen when running OctoPrint in safe mode?
This continues to happen in safe mode

#### Version of OctoPrint
1.3.11
#### Operating System running OctoPrint
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
```

#### Printer model & used firmware incl. version

iTopie running Klipper

#### Browser and version of browser, operating system running browser

Chromium 76.0.3809.100
Firefox 68.0.2

#### Link to octoprint.log

https://gist.github.com/dkulinski/c81ecb068f1771cce9b3b30f05d258fc

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser
```
Did not bind view model bedlevelvisualizerViewModel to target #wizard_plugin_bedlevelvisualizer since it does not exist
packed_core.js:2475 User dan logged in
packed_core.js:15967 ... binding done
packed_core.js:15979 Application startup complete
VM10072:1 POST https://octopi.lan/plugin/appkeys/decision/f79c74b29a06eaff6bcae4bc87a8a70e 404 (NOT FOUND)
```

#### Screenshot(s)/video(s) showing the problem:

N/A

I have read the FAQ.

**Comment by foosel** [comment] 2019-09-04 08:42
If the decision endpoint returns 404, that means the `user_token` for the pending decision couldn't be found. Note that pending decisions will be considered stale and removed if the polling endpoint isn't called in an interval <5s.

I'd need some more information on your client setup and implementation in order to dive into this. Right now it sounds like something made the pending decision go stale and that in turn caused the 404. What's weird is that the result poll should also start returning a 404 in that case instead of a 202, but to understand why that is I'd need more info on the client first and ideally a set of requests & timings to fire off against the API to reproduce, because right now I can't reproduce it at all.

```
2019-09-04 10:39:23,016 - tornado.access - INFO - 201 POST /plugin/appkeys/request (::1) 5.00ms
2019-09-04 10:39:24,953 - tornado.access - INFO - 202 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 6.00ms
2019-09-04 10:39:26,818 - tornado.access - INFO - 202 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 6.00ms
2019-09-04 10:39:28,467 - tornado.access - INFO - 202 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 6.00ms
2019-09-04 10:39:31,030 - tornado.access - INFO - 202 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 5.00ms
2019-09-04 10:39:33,450 - tornado.access - INFO - 202 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 6.00ms
2019-09-04 10:39:35,693 - tornado.access - INFO - 202 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 6.00ms
2019-09-04 10:39:37,098 - tornado.access - INFO - 204 POST /plugin/appkeys/decision/4ae4c110dbd54ebddc92755d37f5c586 (::1) 8.00ms
2019-09-04 10:39:39,078 - tornado.access - INFO - 200 GET /plugin/appkeys/request/9160be1212a7614191eded70138a60f1 (::1) 6.00ms
```

**Comment by dkulinski** [comment] 2019-09-05 03:52
In terms of client, if you are asking about the browser I have tried both Chromium and Firefox.  Eventually I'm hoping to make an app to help orchestrate multiple Octoprint instances.  The code is just me testing the appkeys functionality and is located here: https://github.com/dkulinski/aquarium.

The OctoPrint instance is an OctoPi installation that has been upgraded over the past 2 years I believe.  I'll redeploy on a spare Raspberry Pi that I have sitting around and test from there to make sure something broken hasn't been lingering for a while.

**Comment by foosel** [comment] 2019-09-05 12:19
The good news is, I can reproduce what you are seeing with your client code. The bad news is, right now I don't understand it.

**Comment by foosel** [comment] 2019-09-05 12:41
Found it. The issue is that you set `user` to an empty string instead of just leaving it out. The code wasn't prepared for that... backend required matching of user name to an empty string, frontend however didn't, and so you got a confirmation dialog which then couldn't get resolved in the backend.

The above commit fixes this by ignoring empty user ids on the API. You should also adjust your client though to simply not send a user id instead of an empty one, like documented.

Patch is available on `maintenance`, soon `devel` and will be part of 1.3.12.

**Closed** 2019-10-22 09:59 UTC
Labels: status:solved, type:confirmed bug
