### ISSUE TITLE
[Request] Save terminal settings

### ISSUE THREAD

**Issue by quillford** [foosel/OctoPrint#976] opened 2015-07-18 21:10 UTC
It would be nice if octoprint had a button in advanced options to save the user's preference for 'Suppress M105 requests/responses' and 'Suppress M27 requests/responses'.

**Comment by foosel** [comment] 2015-07-20 07:58
Duplicate of #443, exact duplicate of #891

**Closed by foosel** 2015-07-20 07:58 UTC
Labels: type:request
