### ISSUE TITLE
[1.3.10rc3] Failed to install plugins during restore

### ISSUE THREAD

**Issue by varazir** [foosel/OctoPrint#2920] opened 2018-11-29 10:41 UTC
#### What were you doing?

1. Go to 'Backup & restore in the settings'
2. Click on 'Browse...'
3. Clicked on Upload and restore
4. All looked OK no errors. 

E-mailing backups 

#### What did you expect to happen?

All settings and plugins (that is in the repo ) would be  installed/restored

#### What happened instead?

Just few plugins was installed 
Settings set in the main conf file was still there but nothing in the plugin selection 

#### Version of OctoPrint

Backup made on OctoPrint 1.3.10rc2
Restore on OctoPrint 1.3.10rc3 

#### Operating System running OctoPrint

OctoPi 0.15.1

#### Browser and version of browser, operating system running browser

Windows 10, Chrome 

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment] 2018-11-29 11:03
Please don't forget the `octoprint.log`s from restoring and ideally also backup creation, like we talked about on IRC. Thanks!

**Comment by varazir** [comment] 2018-11-29 20:10
Sent a e-mail with the backup

**Comment by foosel** [comment] 2018-11-30 09:12
Got the backups, thank you, but I'm still lacking *the logs*. I need the logs from the instances, not the ones in the backup (they might not have captured everything). Please provide the logs here as discussed.

**Comment by varazir** [comment] 2018-11-30 09:15
Hmm you mean system logs or OctoPrint logs ? the newer backup have all
the logs that are in the Octoprint/logs . Can dubble check that they
are the same.


2018-11-30 10:12 GMT+01:00, Gina Häußge <notifications@github.com>:
> Got the backups, thank you, but I'm still lacking *the logs*. I need the
> logs from the instances, not the ones in the backup (they might not have
> captured everything). Please provide the logs here as discussed.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/foosel/OctoPrint/issues/2920#issuecomment-443139961


-- 
Kind Regards/Mvh
Daniel

**Comment by foosel** [comment] 2018-11-30 10:10
When I say logs I always mean `octoprint.log` (and `serial.log` if applicable) ;) Also says so in the bug reporting template. 

The backups do not contain the restore logs as they were naturally overwritten during restore. And I just realized you also can't produce these since well... they were overwritten. So never mind.

I just checked... you have GCODE System Commands disabled per your config. Fullscreen Webcam had a mismatching identifier on the repository, that will be fixed soon. PidTune and Display ETA aren't registered on the repository. So that explains the non-restored plugins that you so far told me about. 

However, on my reproduction I noticed a TON of wrongly reported compatibility issues that led to a lot of other plugins not being installed. Quick look into the code and I now know what's up, there's a bit of wrong logic in there determining compatibility, and that's causing this issue. So I guess RC4 it will have to be after all 😕 Still, good this was caught in time.

**Comment by foosel** [comment] 2018-11-30 12:01
Yeah, already on that.

**Comment by foosel** [comment] 2018-11-30 16:01
Fixed the issue. Also `logs` won't be part of the backup anymore, neither will be `generated` and `watched`. Makes more sense this way. Fixes will be released with 1.3.10rc4.

**Comment by varazir** [comment] 2018-11-30 17:02
Well I think logs would be good to have in the backup. If you use backup/restore part of troubleshooting.

**Comment by foosel** [comment] 2018-11-30 19:05
The plan was to have the restore log in place, since that is the more informative anyhow. However I just noticed an issue with that. Correcting this is too invasive for an RC fix, so logs will have to wait until 1.3.11.

**Comment by foosel** [comment] 2018-12-03 13:53
1.3.10rc4 is out

**Closed by foosel** 2018-12-03 13:53 UTC
Labels: status:solved, type:confirmed bug
