### ISSUE TITLE
[Request] GCode Viewer Defaults

### ISSUE THREAD

**Issue by chadwalber** [foosel/OctoPrint#702] opened 2015-01-03 15:48 UTC
Every time I open the GCode Viewer Tab, I have to set the renderer options. Is there a way to make these options the defaults for when I load the tab?

**Comment by Klikini** [comment] 2015-01-03 17:33
Could the last-used options be set per-user in users.yaml?

**Comment by chrisbcole** [comment] 2015-03-01 19:53
I also find this frustrating.

**Comment by eboston** [comment] 2015-03-01 20:03
And how about adding an option to control how big a gcode file is before triggering the "it's too big"  warning.

**Comment by Klikini** [comment] 2015-03-05 01:07
Yes, I get that for files that I have no problem with.

**Comment by asraelis** [comment] 2015-03-14 09:31
I can not watch gcode viewer if I am using large gcodes as well. Unfortunately I can not see the gcode viewer after clicking on "OK" as well :-(. 
Anyway it's a super printing software and I am happy that I decided to use octoprint ;-)

**Comment by foosel** [comment] 2015-03-23 13:08
Duplicate of #443

**Closed by foosel** 2015-03-23 13:08 UTC
Labels: status:duplicate, type:request
