### ISSUE TITLE
[Request] Save position before a pause

### ISSUE THREAD

**Issue by quillford** [foosel/OctoPrint#917] opened 2015-05-29 20:17 UTC
Since OctoPrint allows jogging and homing if a print is paused, OctoPrint should save the last position before the pause so that it can resume that position after the print is resumed as slicers do not set the position on all axes for every move.

**Comment by foosel** [comment] 2015-09-08 14:08
Duplicate of #366

**Closed by foosel** 2015-09-08 14:08 UTC
Labels: type:request
