### ISSUE TITLE
[request] Please show Z-Height (again)

### ISSUE THREAD

**Issue by Lord2Vader** [foosel/OctoPrint#1055] opened 2015-09-09 10:20 UTC
In previus versions i had an indicator for the z height so i knew when to watch out for critical moments in the print such as bridges or thin walls.

Could you please refit it in the status section?

BR Vader

**Comment by markwal** [comment] 2015-09-12 16:53
I think this is a duplicate of #355

**Comment by foosel** [comment] 2015-09-22 11:27
And of #1046. There's a reason it got removed, outlined in #1046. The z-height that used to be reported in the UI was inaccurate most of the time.

If you want to be notified about certain "critical moments" in the print, something like injected custom codes inside those printed files combined with a gcode hook in a plugin might make more sense. 

Alternatively try [this plugin](https://github.com/foosel/OctoPrint-DisplayZ).

**Closed by foosel** 2015-09-22 11:27 UTC
Labels: type:request
