### ISSUE TITLE
Feature Request - On/Off button for video feed

### ISSUE THREAD

**Issue by InnovationSystemsAU** [foosel/OctoPrint#464] opened 2014-05-05 01:40 UTC
Hi,

Sometimes the video feed can saturate the bandwidth on a connection and it is not practical to constantly run it. Can we have a switch to enable/disable this on the control page?

Thanks.

**Comment by foosel** [comment] 2016-03-10 14:32
Duplicate of #368

**Closed by foosel** 2016-03-10 14:32 UTC
Labels: plugin-only, type:request
