### ISSUE TITLE
[Request] Folders Feature on Store Locally Files

### ISSUE THREAD

**Issue by BLeaCHeR** [foosel/OctoPrint#1042] opened 2015-09-02 06:08 UTC
Hi Guys:

Thanks for your efford, i like octoprint (Actually i use it on my Raspi) and i want to suggest the posibility of make folders for files that are stored on the octoprint, with that, the stl files can be more organizated.

i hope you like my sugestion. (and sorry for my english)

Daniel B.

**Comment by foosel** [comment] 2015-09-02 06:11
Duplicate of #31

**Closed by foosel** 2015-09-02 06:11 UTC
Labels: type:request
