### ISSUE TITLE
[Request]Delay timelapse start

### ISSUE THREAD

**Issue by jneilliii** [foosel/OctoPrint#667] opened 2014-12-10 05:06 UTC
Timelapse on timer mode starts taking snapshots immediately when print starts.  Would prefer the recording to begin after the bed has completely heated instead of wasting the disk space taking snapshots of the same still image as the bed is heating.  Workaround is obviously to pre-heat the bed prior to sending the print job, but think it would make more logical sense to begin timelapse recording on homing the axis or during the printing of the first layer.

**Comment by foosel** [comment] 2016-02-02 16:33
There was a duplicate of this ticket with #1164. Normally I'd close the duplicate, since it came later, but since I didn't notice the duplication and there is actually some interesting commenting going on in the other ticket, I'm closing this one now instead. Sorry... I really wish Github would let me merge tickets for cases like this, it doesn't however :/

**Closed by foosel** 2016-02-02 16:33 UTC
Labels: type:request
