### ISSUE TITLE
Octoprint looses USB connection with printer repeatedly

### ISSUE THREAD

**Issue by davidsielert** [foosel/OctoPrint#2649] opened 2018-05-18 06:18 UTC
#### What were you doing?

1. Uploaded via Cura
2. Started print
3. ...

#### What did you expect to happen?
Finish print
#### What happened instead?
Print stopped mid print about 2 hours in , has happened 3 times in a row now
#### Did the same happen when running OctoPrint in safe mode?
haven't tried that

#### Version of OctoPrint
OctoPrint 1.3.8 

#### Operating System running OctoPrint
running on OctoPi 0.14.0

#### Printer model & used firmware incl. version
Ender 3 th3d unified (marlin) latest

#### Browser and version of browser, operating system running browser
Chrome on windows and osx

#### Link to contents of terminal tab or serial.log

Logs are too big for gist.. Placed in public dropbox folder 
https://www.dropbox.com/sh/ivpnj9x06hcpoh8/AAC7BgmYG8RPMa-7vdhxe_o9a?dl=0

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.
dmesg from octopi
```
[Fri May 18 04:31:38 2018] Bluetooth: Core ver 2.22
[Fri May 18 04:31:38 2018] NET: Registered protocol family 31
[Fri May 18 04:31:38 2018] Bluetooth: HCI device and connection manager initialized
[Fri May 18 04:31:38 2018] Bluetooth: HCI socket layer initialized
[Fri May 18 04:31:38 2018] Bluetooth: L2CAP socket layer initialized
[Fri May 18 04:31:38 2018] Bluetooth: SCO socket layer initialized
[Fri May 18 04:31:38 2018] Bluetooth: HCI UART driver ver 2.3
[Fri May 18 04:31:38 2018] Bluetooth: HCI UART protocol H4 registered
[Fri May 18 04:31:38 2018] Bluetooth: HCI UART protocol Three-wire (H5) registered
[Fri May 18 04:31:38 2018] Bluetooth: HCI UART protocol Broadcom registered
[Fri May 18 04:31:38 2018] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[Fri May 18 04:31:38 2018] Bluetooth: BNEP filters: protocol multicast
[Fri May 18 04:31:38 2018] Bluetooth: BNEP socket layer initialized
[Fri May 18 04:31:52 2018] random: crng init done
[Fri May 18 04:31:52 2018] random: 7 urandom warning(s) missed due to ratelimiting
[Fri May 18 06:04:32 2018] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri May 18 06:04:32 2018] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri May 18 06:04:33 2018] usb 1-1.3: USB disconnect, device number 4
[Fri May 18 06:04:33 2018] ftdi_sio ttyUSB0: error from flowcontrol urb
[Fri May 18 06:04:33 2018] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[Fri May 18 06:04:33 2018] ftdi_sio 1-1.3:1.0: device disconnected
[Fri May 18 06:04:33 2018] usb 1-1.3: new full-speed USB device number 5 using dwc_otg
[Fri May 18 06:04:33 2018] usb 1-1.3: New USB device found, idVendor=0403, idProduct=6001
[Fri May 18 06:04:33 2018] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Fri May 18 06:04:33 2018] usb 1-1.3: Product: FT232R USB UART
[Fri May 18 06:04:33 2018] usb 1-1.3: Manufacturer: FTDI
[Fri May 18 06:04:33 2018] usb 1-1.3: SerialNumber: A107BRGW
[Fri May 18 06:04:33 2018] ftdi_sio 1-1.3:1.0: FTDI USB Serial Device converter detected
[Fri May 18 06:04:33 2018] usb 1-1.3: Detected FT232RL
[Fri May 18 06:04:33 2018] usb 1-1.3: FTDI USB Serial Device converter now attached to ttyUSB0
[Fri May 18 06:09:34 2018] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri May 18 06:09:34 2018] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri May 18 06:09:34 2018] usb 1-1.3: USB disconnect, device number 5
[Fri May 18 06:09:34 2018] ftdi_sio ttyUSB0: error from flowcontrol urb
[Fri May 18 06:09:34 2018] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[Fri May 18 06:09:34 2018] ftdi_sio 1-1.3:1.0: device disconnected
[Fri May 18 06:10:26 2018] usb 1-1.3: new full-speed USB device number 6 using dwc_otg
[Fri May 18 06:10:26 2018] usb 1-1.3: New USB device found, idVendor=0403, idProduct=6001
[Fri May 18 06:10:26 2018] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Fri May 18 06:10:26 2018] usb 1-1.3: Product: FT232R USB UART
[Fri May 18 06:10:26 2018] usb 1-1.3: Manufacturer: FTDI
[Fri May 18 06:10:26 2018] usb 1-1.3: SerialNumber: A107BRGW
[Fri May 18 06:10:26 2018] ftdi_sio 1-1.3:1.0: FTDI USB Serial Device converter detected
[Fri May 18 06:10:26 2018] usb 1-1.3: Detected FT232RL
[Fri May 18 06:10:26 2018] usb 1-1.3: FTDI USB Serial Device converter now attached to ttyUSB0
```

**Comment by foosel** [comment] 2018-05-18 07:49
What I see in your `dmesg` output is that the driver ran into an error and the USB device that's your printer got reported as disconnected twice. That `dmesg` entry at 06:04 also coincides with the `SerialException` logged in `octoprint.log` (compare the timestamps), so my money would be that this is the cause of that exception. Which makes it a problem outside of OctoPrint's control - if the OS OctoPrint is running on is even losing sight of the serial connection, there's *nothing* that OctoPrint can do about it.

I can't tell you anything that isn't already listed in [this FAQ entry](https://discourse.octoprint.org/t/octoprint-randomly-loses-connection-to-the-printer-with-a-serialexception/228?u=foosel). 

Since this isn't an issue OctoPrint can solve, I'm closing this bug, but you are welcome to get in touch on the [community forum](https://discourse.octoprint.org), maybe someone there has a hint that might help you solve this.

**Closed by foosel** 2018-05-18 07:49 UTC
Labels: type:potential bug

**Comment by davidsielert** [comment] 2018-06-10 02:50
@foosel Seriously alot of people are experiencing this with reccomended hardware and setups trying all the given solutions does nothing to fix it

**Comment by foosel** [comment] 2018-06-12 07:43
Then I suggest all of those people get together in a mega thread on this issue on the [community forum](https://discourse.octoprint.org) and maybe that way we can find further possible solutions (or at least figure out the common denominator).

But as I said - when the *underlying operating system* reports the machine as disconnected, there's nothing OctoPrint running on that OS can do to fix it (or prevent it). It's the same as if you'd pulled out the USB connector from the point of view of OctoPrint here.
