### ISSUE TITLE
[REQUEST] Add ambient temperature to graph display... or at least somewhere in the GUI

### ISSUE THREAD

**Issue by bolsoncerrado** [foosel/OctoPrint#994] opened 2015-07-28 10:56 UTC
I'm willing to monitor an extra tempterature sensor, perhaps whenever i enclose my printer into a cabinet so I can trigger fans to cool electronics or whatever else... wondering if there's a way to add extra temperature sensor readings somewhere in the GUI to display...

**Comment by foosel** [comment] 2015-07-28 11:06
Duplicate of #321 (easily found when searching for "temperature" btw ;))

**Closed by foosel** 2015-07-28 11:06 UTC
