### ISSUE TITLE
Feature Request: Snap picture after print is finished

### ISSUE THREAD

**Issue by nicolinux** [foosel/OctoPrint#436] opened 2014-04-09 23:21 UTC
As we all know, 3D printing is often a hit or miss business. So it is very important to have the possibility to look at gcode files later (expecially if one uses a cool slicer like Cura that saves the slicing settings inside the gcode file).
It would be very useful if OctoPrint could snap a picture after the print has finished and link it to the print job (and gcode file). This way one could later inspect the print quality and adjust the slicing settings.

**Comment by foosel** [comment] 2015-03-23 12:37
Duplicate of #391 if I'm not mistaken?

**Closed by foosel** 2015-03-23 12:37 UTC
Labels: type:request
