### ISSUE TITLE
Problem with Temp Chart

### ISSUE THREAD

**Issue by KC703** [foosel/OctoPrint#1928] opened 2017-05-20 14:54 UTC
#### What were you doing?
While normal printing the temperature graph is not displaying accurate temps.  

The issue may be related to GCODE Scripts within Octoprint, I use a "Start script" to preheat my bed prior to heating the hotend:
M190 S85
Basically, when the bed reaches 85C, start the print which heats the hotend to 245C and bed to 110C.

On the LCD screen of the printer, the temps are correct as sliced.

#### What did you expect to happen and what happened instead?
The temp graph to display the temp of the bed and hotend.

#### Branch & Commit or Version of OctoPrint
OctoPrint 1.4.0.dev368+g3e5d82c (devel branch

#### Operating System running OctoPrint
Raspberry Pi (Octopi)

#### Printer model & used firmware incl. version
Lulzbot TAZ 5, Marlin 1.0.0

#### Browser and Version of Browser, Operating System running Browser
Windows 10, Chrome  Version 58.0.3029.110 (64-bit)

#### Link to octoprint.log

[On gist.github.com or pastebin.com. ALWAYS INCLUDE and never truncate.]

#### Link to contents of terminal tab or serial.log
https://www.dropbox.com/s/0d7pk08ocf72k92/serial.log?dl=0

#### Link to contents of Javascript console in the browser

[On gist.github.com or pastebin.com or alternatively a screenshot. If applicable -
always include if unsure or reporting UI issues.]

#### Screenshot(s) or video(s) showing the problem:
The following picture is the temp graph at the end of my GCODE Start script:
![octoprint - 2printstart](https://cloud.githubusercontent.com/assets/7727874/26276710/8bcdc674-3d4a-11e7-990d-919f86241ec4.JPG)

During Printing:
![octoprint - 3printing](https://cloud.githubusercontent.com/assets/7727874/26276709/82e06d00-3d4a-11e7-9e05-98e685449318.JPG)

Later in the Print:
![octoprint - 4printing2](https://cloud.githubusercontent.com/assets/7727874/26276708/79ffe4d6-3d4a-11e7-85da-79289f593186.JPG)

A picture of the LCD Screen of the printer showing correct temps:
![octoprint - 2blcddisplay](https://cloud.githubusercontent.com/assets/7727874/26276706/6c4564ce-3d4a-11e7-82a7-86dc5cc31af8.JPG)

Yes, I have read the FAQ.

**Comment by KC703** [comment] 2017-05-21 00:57
I forgot to add that this issue started in the recent two commits (~5/17)

**Comment by foosel** [comment] 2017-05-22 12:53
Hm, I cannot reproduce this. Testing with the exact same version, currently printing and happily reporting the (correct) temperature.

What I notice from your provided `serial.log` is that your firmware decides it's done heating your hotend to 245°C when it has only reached 235°C:

```
2017-05-20 14:00:43,611 - Recv: T:225.4 E:0 W:?
2017-05-20 14:00:44,611 - Recv: T:226.6 E:0 W:?
2017-05-20 14:00:45,612 - Recv: T:228.1 E:0 W:?
2017-05-20 14:00:46,613 - Recv: T:229.1 E:0 W:?
2017-05-20 14:00:47,619 - Recv: T:230.2 E:0 W:?
2017-05-20 14:00:48,619 - Recv: T:231.6 E:0 W:?
2017-05-20 14:00:49,664 - Recv: T:232.9 E:0 W:?
2017-05-20 14:00:50,663 - Recv: T:234.1 E:0 W:?
2017-05-20 14:00:51,666 - Recv: T:235.5 E:0 W:0
2017-05-20 14:00:51,851 - Recv: ok
```

And the reason your temperature graph then doesn't update is that for some reason OctoPrint apparently is not sending out `M105` queries at all to retrieve the temperature. The `octoprint.log` might give some hints as to why - please also provide that, it's missing up there. Also try to reproduce the problem in safe mode please, to rule out any plugins from interfering here.

**Comment by nophead** [comment] 2017-05-22 14:54
Looks like the wait time is set to 0 which is not the best idea. Just because the heater block has got to temperature (or not in this case) it takes some time for the filament to catch up and for some hot ends to expand to the normal length.

**Comment by KC703** [comment] 2017-05-23 03:33
Thanks for looking into this.  I did a little more testing, and unloaded a
few plugins which I wasn't using.  Unloading the "Tempsgraph" and the
regular Octoprint graph is working.

How do you enable a disabled plugin... the radio button disappears, leaving
just the trashcan to delete the plugin.


Regarding the "0" wait time, I usually print a skirt or brim to ensure the
hotend is primed...  :-)


Safe to close this issue.  Thanks!

**Comment by foosel** [comment] 2017-05-23 08:10
@KC703 huh... I thought that plugin was frontend only, which wouldn't explain why no `M105` is sent (that's a quite crucial part of the communication layer deep down in the backend). 

Happy to hear that disabling the plugin resolved it for you, but I'm wondering *why* ;)

Re enabling disabled plugins:

![issue_1928](https://cloud.githubusercontent.com/assets/83657/26344441/e904cb60-3f9f-11e7-9983-ca7e98f66945.gif)

But enabling plugins that are not bundled is disabled in safe mode, so if you are running that, that would explain it.

Closing since apparently the problem was caused by a plugin (even though I don't understand that ;))

**Closed by foosel** 2017-05-23 08:10 UTC
Labels: status:unreproduced

**Comment by KC703** [comment] 2017-05-23 19:49
Hmm... I don't think I'm in "Safe Mode".  Here's what I see when trying to
re-enable plugins.
[image: Inline image 1]

**Comment by foosel** [comment] 2017-05-24 08:29
@KC703 can you go to the Github issue and post the image there instead of replying to the mail? The image didn't make it through.

**Comment by KC703** [comment] 2017-05-25 03:19
Sorry.  Here's what I see when trying to re-enable plugins: 
![octoprint - plugin radiol](https://cloud.githubusercontent.com/assets/7727874/26434528/4c011196-40d7-11e7-9eb8-31fa47c3ee5d.JPG)

The radio button is missing.

**Comment by foosel** [comment] 2017-05-29 11:54
@KC703 That turned out to be a bug introduced by #1915, because it was referring to a non existing icon class. That's been fixed with the above commit (which should be present on the `maintenance` and `devel` branches)

**Comment by KC703** [comment] 2017-05-29 17:25
Hmm... I'm running:
OctoPrint 1.4.0.dev387+g905c05b (devel branch)

It looks to still be present?

**Comment by KC703** [comment] 2017-05-29 21:17
Sorry that last message may have been premature. 

Just received an update to OctoPrint 1.4.0.dev389+g528bbba (devel branch) and the radio button to enable/disable the plugin is back.

Thanks!
Ken

**Comment by foosel** [comment] 2017-05-30 07:27
👍
