### ISSUE TITLE
[Request] Get confirmation before canceling a job

### ISSUE THREAD

**Issue by foofoodog** [foosel/OctoPrint#687] opened 2014-12-19 03:27 UTC
How about if someone clicks the cancel job button you confirm they actually want to cancel the job?
Say a dialog that says something like "You are {{elapsedTime}} into printing a job on printer {{printerName}} for file {{filename}} with {{remainder}} left. Are you sure you want to cancel?

e.g.
"You are 10 hours into printing a job on printer 3DMetlalDust for file Darth_Helmet.gcode  with 1 hours left. Are you sure you want to cancel?"

I love cookies made from PLA.

**Comment by AlaskanShade** [comment] 2015-01-12 17:56
The disconnect button could use a confirmation as well.  I was checking my printer from my phone and it initially came up with the connection lost dialog.  When I went to hit the reconnect button, the dialog disappeared and I ended up hitting the disconnect button instead.  I tinkered with how to resume the print (without luck), but it turned out I wanted to resize it anyway so I gave up.

**Comment by shanselman** [comment] 2015-02-06 20:00
Yes, I'd definitely be in favor of more confirmations or at least the option to turn them all on, per #748. I deleted a nice Timelapse because the button is so close to download.

**Comment by fieldOfView** [comment] 2015-10-22 09:59
> As long as there is the option to not have it (in settings).

In settings, and/or as a "Don't show this confirmation again" checkbox

**Comment by foosel** [comment] 2016-12-18 15:49
Just now realized we had a duplicate of that with #1550 which has since been implemented in 1.3.0. Also that's going to be made optional again with 1.3.1 (see #1638) since of course now there is a confirmation dialog the other half of the user base is complaining about this fact. Hooray ;)

**Closed by foosel** 2016-12-18 15:49 UTC
Labels: type:request

**Comment by BillyBlaze** [comment] 2016-12-18 16:27
Just my two cents on this matter; isn't it better if we would refactor the showConfirmationDialog function with the notification component (PNotify) instead of a modal? I think that would also be more consistent with features such as the update confirmation.

(Perhaps it would be also a good idea to move the settings check within that function, so its only declared once)

**Comment by foosel** [comment] 2016-12-18 16:58
Imho a modal reflects "I need a decision from you right now and can't continue until I have that" better than the "oh, btw..." style of the notifications.
