### ISSUE TITLE
Octopi or Octoprint requires reading the canvas to show temperature graph

### ISSUE THREAD

**Issue by oUToWEROfeCtICIonselMOni** [foosel/OctoPrint#2227] opened 2017-11-17 02:17 UTC
What were you doing?

Octopi/OctoPrint seems to require read access of the canvas (a web technology) to display the temperature graph. When I set CanvasBlocker 0.4.2 to prompt me whenever something tries to read the canvas, and deny the request, Octoprint will show me the temperature graph. However, if I only allow the whitelist, if Octopi.local is not in the list, I do not see any data for the temperature graph. If I whitelist Octopi.local, I see the temperature graph like normal.
What did you expect to happen?

That neither Octopi nor OctoPrint require access to the canvas, nor try to read it. Reading the canvas is a tracking technique, why is Octoprint using it?
What happened instead?

Temperature graph stopped working. The rest of the UI works fine*.
Did the same happen when running OctoPrint in safe mode?

N/A?
Branch & Commit or Version of OctoPrint

Ocroprint 1.2.7
I know it's kind of old, but it can't update itself for some reason. However, unless you've specifically fixed this, I don't think it's going to be fixed in a later release. This is more of a design "problem" than a bug. Someone somewhere decided to read the canvas, and I'd like you to undecide to do so. plz/thx.
Operating System running OctoPrint

Octopi 1.2.7
Printer model & used firmware incl. version

N/A, it's a web technology problem.
Browser and Version of Browser, Operating System running Browser

Firefox 56.0.2
CanvasBlocker 0.4.2
Link to octoprint.log
Link to contents of terminal tab or serial.log
Link to contents of Javascript console in the browser
Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment] 2017-11-17 08:59
Duplicate of #2224 in which I already stated that OctoPrint is not using that "readout API" (and in fact have since confirmed by also installing that extension in question, without any issues).

Do not simply keep opening the same issue over and over again.

**Closed by foosel** 2017-11-17 08:59 UTC
