### ISSUE TITLE
[Request] Script + buttons

### ISSUE THREAD

**Issue by MLWORKX** [foosel/OctoPrint#674] opened 2014-12-10 20:03 UTC
RepetierHost has e.g. 5 slots for self written sripts which I use for load and unload extruder 1 and 2 plus switch my LEDs on on slot 5

Really nice would be to be able to have 10 slots for scripts:
- name the scripts as defined by the user
- creating a script creates a button at the buttom of the control panel

**Comment by rspeed** [comment] 2015-01-05 07:16
Sounds like a duplicate of #463.

**Comment by MLWORKX** [comment] 2015-01-05 18:54
ohh, haven't seen that- #463 is exacly what I need!

**Comment by foosel** [comment] 2015-02-04 23:48
Custom controls are already a thing, just edit your ``config.yaml`` for now.

**Closed by foosel** 2015-02-04 23:48 UTC
Labels: type:request
