### ISSUE TITLE
[Request] Show the current baudrate

### ISSUE THREAD

**Issue by DominikPalo** [foosel/OctoPrint#2859] opened 2018-10-21 16:06 UTC
It would be nice if OctoPrint shows somewhere the baudrate of the connection when it is used in the auto mode, because now it is not possible (at least I didn't find a way how to) get the current baudrate. For example as a tooltip on the "Disconnect" button the connection panel, or somewhere in the terminal tab. 
![image](https://user-images.githubusercontent.com/1623257/47269241-415aa580-d55b-11e8-8a1c-82f25ef96fd9.png)

**Comment by foosel** [comment] 2018-10-30 15:00
Partially implemented as a side effect of the fix/implementation of #2740. The commit above fully implements it that the current settings are now reflected in the selection boxes after a connection has been established:

![image](https://user-images.githubusercontent.com/83657/47727559-e7459880-dc5c-11e8-8ce5-40a91e4b5db4.png)

Pushed to `maintenance`, soon `devel`, to be released with 1.3.10

**Comment by foosel** [comment] 2018-11-14 17:32
You aren't wrong and that should be implemented. The problem is that it works here, both of these were set to AUTO before connecting:

![image](https://user-images.githubusercontent.com/83657/48500617-91b3e300-e83b-11e8-8ca8-7ecee6ad9d06.png)

Does it work in safe mode? Have you tried clearing your browser's cache?

**Comment by foosel** [comment] 2018-11-14 17:33
Ooooh, wait. Did that connection happen through auto connect on server startup or through a manual connect?

**Comment by DominikPalo** [comment] 2018-11-18 20:48
It was a manual connect. See my video (recorded in the incognito mode, so it can't be caused by the browser's cache) https://gyazo.com/d9114fd8ac759e6e09ca217da04b08c2

**Comment by foosel** [comment] 2018-12-10 16:06
This not working under 1.3.10 is still unreproduced. Marking as such.

**Comment by foosel** [comment] 2019-01-28 16:57
@Edo78 exact steps with which you experience this issue. The more details the better. I still cannot reproduce this.

**Comment by Edo78** [comment] 2019-01-28 20:31
I did nothing special:

- Downloaded octopi
- flashed on the sd
- configured the wifi
- booted the Pi
- if I remember correctly on the first login it tells me there's an update so I update
- rebooted the Pi and reloaded in the browser
- connected to the printer with AUTO/AUTO
- keep seeing AUTO/AUTO since then

I even tried the incognito mode in chrome but I stile get AUTO/AUTO.

If I set the proper values then I see them, otherwise it's always been AUTO/AUTO

**Comment by foosel** [comment] 2019-03-19 12:25
Now that was weird. I couldn't reproduce it at all - until today. Now I finally could reproduce it and looking at the code have no idea why it ever worked for me to begin with. I'm... very confused by this 🤨

In any case, I hope the above commit now fixes it for good - it does for me. Already pushed to `maintenance`, soon `devel`, to be part of 1.3.11.

**Closed** 2019-05-14 09:04 UTC
Labels: status:solved, type:confirmed bug, type:request
