### ISSUE TITLE
Support for consecutive prints with Timelapse

### ISSUE THREAD

**Issue by szafran81** [foosel/OctoPrint#442] opened 2014-04-14 09:11 UTC
Hi,

There's a problem with the timelapse creation. If I start printing next print before the timelapse compression of the previous print finishes than that timelapse becomes unfinished and the snapshots are deleted. I think that it would be nice for OctoPrint to create subfolders int the timelapse tmp folder, and only remove those snapshots for which the timelapse video was succesfully created. And after starting OctoPrint should check if there re any unfinished videos to compress, and run the compression if neccesary.

Szafran

**Comment by foosel** [comment] 2015-03-23 12:49
Duplicate of #318

**Closed by foosel** 2015-03-23 12:49 UTC
Labels: type:request
