### ISSUE TITLE
Files API gets "out-of-sync"

### ISSUE THREAD

**Issue by UnchartedBull** [foosel/OctoPrint#3446] opened 2020-02-06 23:59 UTC
#### What were you doing?

1. Delete a file via the normale WebInterface
2. Query the files API
3. Find the file, that is deleted and is NOT shown in the normal Web UI anymore

Also occurs for uploading a file sporadically, couldn't identify a pattern yet, though ... A user of a Touch UI I'm currently working on also reported a similar error with the GCode Analysis not being available in the API, while being available in the Web UI (https://github.com/UnchartedBull/OctoDash/issues/400). A restart of OctoPrint normally fixes the issue and everything is showing up correctly.

#### What did you expect to happen?
The deleted/uploaded/changed file to be correctly updated in the API

#### What happened instead?
File info gets updated in the OctoPrint UI, but NOT for the API.

#### Did the same happen when running OctoPrint in safe mode?
Haven't tested that yet, just started a longer print I don't want to cancel. If that is important I can test that in around 30 hours. But I don't think a Plugin would tinker with the files API, as this is standard OctoPrint.

#### Version of OctoPrint
1.3.12

#### Operating System running OctoPrint
Debian 10

#### Printer model & used firmware incl. version
Ender-3 Pro with Marlin 2.0

#### Browser and version of browser, operating system running browser
MacOS, Google Chrome 79.0.3945.130 (but happened with other Chrome Builds as well)

#### Link to octoprint.log
https://pastebin.com/UdwyhRvn (didn't see anything useful there)

#### Link to contents of terminal tab or serial.log
not available

#### Link to contents of Javascript console in the browser
![Screenshot 2020-02-07 at 00 55 11](https://user-images.githubusercontent.com/19818061/73988965-8cf9b400-4944-11ea-82b1-4b857bf4fff4.png)

Currently using an old mac, due to the other one being in for a repair ... The UI is still very slow though, I'm currently trying to figure out why. If something jumps to your eye let me know :)

#### Screenshot(s)/video(s) showing the problem:
OctoPrint UI:
![Screenshot 2020-02-07 at 00 44 12](https://user-images.githubusercontent.com/19818061/73988426-fe386780-4942-11ea-9796-640c91b39de8.png)

Files API for folder demo:
![Screenshot 2020-02-07 at 00 42 17](https://user-images.githubusercontent.com/19818061/73988433-042e4880-4943-11ea-8929-8059bf8fa295.png)

I have read the FAQ.

**Comment by foosel** [comment] 2020-02-07 07:32
Sounds like a duplicate of #3422

**Closed by foosel** 2020-02-07 07:32 UTC
Labels: type:potential bug
