### ISSUE TITLE
octoprint.util.comm - ERROR - Exception while processing line

### ISSUE THREAD

**Issue by Naesstrom** [foosel/OctoPrint#1841] opened 2017-03-27 13:24 UTC
#### What were you doing?
Started a new print of the floating photo frames

#### What did you expect to happen and what happened instead?
Octoprint lost connection

#### Branch & Commit or Version of OctoPrint
OctoPrint 1.3.2 (master branch)

#### Operating System running OctoPrint
Octopi

#### Printer model & used firmware incl. version
RepRappro Mono Mendel with Marlin 1.1.0-RC8

#### Browser and Version of Browser, Operating System running Browser
Windows 10, latest chrome browser

#### Link to octoprint.log
https://gist.github.com/Naesstrom/6fcff6c0e48e6c71f267caedeb79255d

**Comment by foosel** [comment] 2017-03-27 13:29
This ticket is incomplete. What you did provide though looks like a duplicate of #1838

**Closed by foosel** 2017-03-27 13:29 UTC
