### ISSUE TITLE
[Request] 3D, rotatable slicer like view in GCODE viewer

### ISSUE THREAD

**Issue by pentar25** [foosel/OctoPrint#1972] opened 2017-06-15 22:05 UTC
Self explanatory. Would be very useful. The ability to rotate the live Gcode view as it prints, and view from different angles.

Thanks

**Comment by ntoff** [comment] 2017-06-16 05:44
https://github.com/foosel/OctoPrint/issues/267 goes into why it's not implemented

**Comment by foosel** [comment] 2017-06-19 08:53
And this is actually a duplicate of that ticket, so closing this. Thanks @ntoff for looking up the ticket!

**Closed by foosel** 2017-06-19 08:53 UTC
Labels: type:request
