### ISSUE TITLE
[request] More than one camera

### ISSUE THREAD

**Issue by Lord2Vader** [foosel/OctoPrint#762] opened 2015-02-08 13:05 UTC
Hi,

would it be possible to implement the feature of using more than one cam?

**Comment by MLWORKX** [comment] 2015-03-11 08:13
+1 on this!    :+1:

**Comment by jneilliii** [comment] 2015-03-11 16:53
+1 on this for me as well.

**Comment by Reisperbachtal** [comment] 2015-03-15 15:34
+1 That would be a nice feature, and if possible also timelapses with picture in picture!

**Comment by foosel** [comment] 2015-03-23 13:06
Duplicate of #401

**Closed by foosel** 2015-03-23 13:06 UTC
Labels: status:duplicate, type:request
