### ISSUE TITLE
[Request] Warn if moves are outside the build envelope

### ISSUE THREAD

**Issue by koenkooi** [foosel/OctoPrint#1020] opened 2015-08-10 11:36 UTC
1. What were you doing?
   I recently bought a Turnigy Fabrikator Mini printer, which as the name implies has a tiny build envelope: 8cm in all directions according to the specs. It only has endstops on Xmin, Ymin and Zmin. I dutifully entered in the sizes in the printer settings. I ran into a few issues:
   - Skipsteps in GUI are still labeled 1/10/100
   - Worse, it generates moves beyond X/Y 80
   - Gcode isn't checked for moves beyond X/Y/Z 80
2. What did you expect to happen?
   What I expected to happen was:
   - Skipstep labels be 1/10/max(100,x,y), so 1/10/80 in this case
   - Cap moves in control panel to buildenvelope, with a warning
   - Pop up a warning when clicking 'print' on gcode that has moves beyong the envelope
3. What happened instead?
   Scary noises when moving Y to 100. The firmware on the printer seems to cap the moves, but it turns about that Y has only 70mm travel, so the firmware capping it around 80mm isn't going to help.
4. Branch & Commit or Version of OctoPrint:  
   the footer says: **1.2.4 (master branch)**
5. Printer model & used firmware incl. version
   Turnigy MiniFabrikator. Internet searches imply it's using marlin, haven't verified that.
6. Browser and Version of Browser, Operating 
   Chrome 44.0.2403 on OSX el Capitan beta
   Chrome 44.0.2403 and Safari on OSX Yosemite
7. Link to octoprint.log 
   Not sure how applicable the log is to the feature request, but here it is :)
   https://gist.github.com/koenkooi/d881acb4c2482b470b65
8. Link to contents of terminal tab or serial.log
   It's empty (-) according to octoprint
9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues):
   N/A
10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues):
    A screenshot showing the skipstep button labels.
    <img width="200" alt="schermafbeelding 2015-08-10 om 13 35 00" src="https://cloud.githubusercontent.com/assets/259525/9170622/bbfce7ca-3f64-11e5-8d55-44a310d2a080.png">

I have read the FAQ.

**Comment by foosel** [comment] 2017-01-27 15:20
Duplicate of #90

**Closed by foosel** 2017-01-27 15:20 UTC
Labels: type:request
