### ISSUE TITLE
[Request] Material buttons to more quickly set temperatures

### ISSUE THREAD

**Issue by light24bulbs** [foosel/OctoPrint#1869] opened 2017-04-14 03:16 UTC
Right now it takes four clicks to set up temperatures for a material.  I have to use the drop down on the bed and the extruder to set the termpatures.  In the empty space under this dialog, I would like buttons that select the material and set that as the temperature.  It would be cool if they had a check mark or turned into a btn-success(green) when they were selected.  

Here is my terrible artists impression.  

![octoprintedited](https://cloud.githubusercontent.com/assets/581906/25032045/e47def60-2085-11e7-9e3f-0b1ceb94d97a.png)

**Comment by ntoff** [comment] 2017-04-14 06:47
You can add your own custom buttons to the "Controls" tab, maybe it'd be nice if that were extended to be able to add custom buttons to any tab? I know for sure I'd use that feature (I  currently have a few temperature buttons in the custom control area).

**Comment by foosel** [comment] 2017-04-18 14:22
This actually does sound like a duplicate of #216, so I suggest to follow that one instead and maybe add a thumbs up to it:

![image](https://cloud.githubusercontent.com/assets/83657/25135619/2c74dae2-2453-11e7-9a2d-444029a46ea5.png)

Closing this one because - as said - it's a duplicate :)

**Closed by foosel** 2017-04-18 14:22 UTC
Labels: type:request

**Comment by light24bulbs** [comment] 2017-04-18 19:01
Ah well...now both threads are closed, and neither has been resolved or answered

**Comment by foosel** [comment] 2017-04-19 07:54
I don't know what you are talking about, #216 is open.
