### ISSUE TITLE
[FEATURE REQUEST] Renderer default options

### ISSUE THREAD

**Issue by bolsoncerrado** [foosel/OctoPrint#871] opened 2015-04-24 08:20 UTC
Ability to SAVE default Renderer options please! ;)

**Comment by foosel** [comment] 2015-04-24 12:40
Duplicate of #443 (as [the search](https://github.com/foosel/OctoPrint/search?q=options&type=Issues) would have revealed)

**Closed by foosel** 2015-04-24 12:40 UTC
