### ISSUE TITLE
[Request] Disable read-only anonymous access

### ISSUE THREAD

**Issue by basdp** [foosel/OctoPrint#1979] opened 2017-06-22 12:05 UTC
I would like to prevent access, also for read only (mostly webcam access and downloading my print files) from not logged in users. As far as I know, this is not possible. Is this something that could be implemented via a plugin?

**Comment by foosel** [comment] 2017-06-22 12:27
Nope, it couldn't, but @Salandora is working on #1110 which will allow that. Webcam access however cannot really be restricted by OctoPrint since OctoPrint is not the webcam server, it merely embeds a stream from it and can't do access control for that.

Closing this since it's basically a duplicate of #1110.

**Closed by foosel** 2017-06-22 12:27 UTC
Labels: type:request

**Comment by Salandora** [comment] 2017-06-23 06:46
Just as a side note here, mjpg_streamer is finally able to bind to an address "output_http -l 127.0.0.1"
This way you can restrict the webcam stream, so no one from outside will be able to connect to it.

Sure you'll stop the webcam stream from the control tab too if you don't use a proxy to become access. But as @foosel once mentioned somewhere you can also restrict the access through the nginx
