### ISSUE TITLE
[Request] [Bug?] Have octopi.local/#control take viewers to the Control tab

### ISSUE THREAD

**Issue by TTN-** [foosel/OctoPrint#1635] opened 2016-12-09 05:40 UTC
Hi everyone :-)

Right now when go to octopi.local/#control it does not load the control tab, it just stays in the Temperature tab.

When I visit octopi.local and click the control tab, the URL changes to octopi.local/#control 

Would it be possible to have the /#control URL take users straight to the Control tab with the webcam feed? The reason I'd like to do this is so that I can give 3D hubs customers an URL that takes them straight to the page with their print (with stats such as print time, percentage complete etc), so that no more buttons have to be pushed to get to the livestream.

Is this a bug?

**Comment by Salandora** [comment] 2016-12-09 08:47
This is a duplicate of #203

Had something like this done once #461, would need to reimplement it if it is wished.
@foosel would you like to have this feature?

**Comment by TTN-** [comment] 2016-12-09 08:54
Sorry, I did make an effort to prevent duplicate issue filings by searching for #control but didn't fine any similar issues.

I'm pretty keen to have this tbh. Not sure how to implement it though.

**Comment by foosel** [comment] 2016-12-09 08:57
@Salandora now that 1.3.0 is out, fire ahead ;) Do it for 1.3.1/`maintenance` even, qualifies as an improvement I think :)

**Comment by foosel** [comment] 2016-12-09 08:57
Closing this because duplicate, please continue any discussions in #203 :)

**Closed by foosel** 2016-12-09 08:57 UTC
Labels: type:request
