### ISSUE TITLE
[Request] Control tab showing (Broken Link image)

### ISSUE THREAD

**Issue by vdirienzo** [foosel/OctoPrint#609] opened 2014-10-08 13:18 UTC
im using octo print 0.10 i have noticed that in the control tab, where it shows the image of the webcam when you dont have the web cam appears a image like its broken link. it will be good to add a logo or image to avoid this when you dont have the web cam connected.

im using firefox.

[IMG]http://i.imgur.com/if14zkc.png[/IMG]

**Comment by rhuuk420** [comment] 2015-12-05 20:29
+1.i've come around to these bugs/feature req's and i'm finding the value of having a bigger webcam view in the control tab that doesn't require me to go to another tab each time to biew the stream as it always shows up as broken on first load. a new default "snapshot" tab that has the webcam and the gcode view in a single side by side pane, and a 20-30mm tall temp graph along the bottom would be an awesome dashboard.

**Comment by foosel** [comment] 2017-01-27 14:33
This is now tracked in #478 which this is somewhat a duplicate of (with differing causes for the request).

**Closed by foosel** 2017-01-27 14:33 UTC
Labels: type:request
