### ISSUE TITLE
After unistall a plugin, octoprint not show me no plugin at all !!

### ISSUE THREAD

**Issue by Gi0cas** [foosel/OctoPrint#2684] opened 2018-06-16 10:03 UTC
#### What were you doing?

I've unistalled a plugin (touchui) and when restarted Octoprint no plugin at all are showed.

#### What did you expect to happen?

I'm expect to have the plugin working...

#### What happened instead?

At the restart, the plugin are not working anymore, and in the plugin Manager they appears like "unistalled" and ready to install, but if i try to install again octoprint gives me error.

#### Did the same happen when running OctoPrint in safe mode?

In Octoprint safe mode plugin are not involved

#### Version of OctoPrint

Version 1.3.8

#### Operating System running OctoPrint

Octoprint on Orange Pi Armbian

#### Printer model & used firmware incl. version

Custom made printer with Klipper firmware

#### Browser and version of browser, operating system running browser

Chrome, Windows 10

#### Link to octoprint.log

https://pastebin.com/er4PA4mf

I have read the FAQ.

**Comment by foosel** [comment] 2018-06-18 07:48
Closing as duplicate of #2625 as already pointed out.

**Closed by foosel** 2018-06-18 07:48 UTC
Labels: type:potential bug
