### ISSUE TITLE
Cannot set initial baudrate detection pause

### ISSUE THREAD

**Issue by yschroeder** [foosel/OctoPrint#2892] opened 2018-11-14 17:07 UTC
#### What were you doing?

1. Open settings menu (click wrench)
2. Go to `Serial Connection > Intervals & timeouts`
3. Change `Initial baudrate detection pause` from 1 to 3 seconds
4. Click Save

#### What did you expect to happen?

`Initial baudrate detection pause` changes from 1 to 3 seconds

#### What happened instead?

 `Initial baudrate detection pause` stayed at 1 second

#### Did the same happen when running OctoPrint in safe mode?

Yes.

#### Version of OctoPrint

1.3.9

#### Operating System running OctoPrint

OctoPi

#### Printer model & used firmware incl. version

Prusa i3 MK2.5, Firmware 3.4.1 (which has another problem which I will address in another issue)

#### Browser and version of browser, operating system running browser

Firefox 63.0.1, Arch Linux 

#### Link to octoprint.log

https://gist.github.com/yschroeder/2a56603323975baeba54ba11449e791c

#### Link to contents of terminal tab or serial.log

Not applicable, printer is not connected.

#### Link to contents of Javascript console in the browser

https://gist.github.com/yschroeder/d711a442314f8db8323121afcb7962d2

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment] 2018-11-14 17:11
Duplicate of #2780, to be fixed in 1.3.10 (and already fixed in the release candidates 1.3.10rc1 and 1.3.10rc2)

**Closed by foosel** 2018-11-14 17:11 UTC
Labels: status:duplicate, type:potential bug
