### ISSUE TITLE
Incorrect grammar on Print Time Left label

### ISSUE THREAD

**Issue by cmadson** [foosel/OctoPrint#2242] opened 2017-11-25 07:09 UTC
#### What were you doing?

Printing a large file that spanned multiple days

#### What did you expect to happen?

When **Print Time Left** reached 1 day, label should read "1 day"

#### What happened instead?

label reads "1 days"

#### Did the same happen when running OctoPrint in safe mode?

I did not attempt this

#### Branch & Commit or Version of OctoPrint

1.3.5 Master

#### Operating System running OctoPrint

OctoPi v 0.14.0

#### Printer model & used firmware incl. version

Lulzbot Taz 6 Marlin_Oliveoil_Tilapia_v1.0.2.22_60d344d.hex

#### Browser and Version of Browser, Operating System running Browser

Safari 10.1

#### Link to octoprint.log

https://gist.github.com/cmadson/f323e04041942dd894395fad2c73300f

#### Link to contents of terminal tab or serial.log

Not included

#### Link to contents of Javascript console in the browser

Not included

#### Screenshot(s)/video(s) showing the problem:

https://www.dropbox.com/s/gzwi25ncq67ruft/screenshot.png?dl=0

I have read the FAQ.

**Comment by foosel** [comment] 2017-11-27 11:46
Thanks for reporting that. Seems to be caused by anything over 24 hours. Fixed on `maintenance`, soon `devel`, will be released with 1.3.6.

**Closed** 2017-12-12 11:53 UTC
Labels: status:solved, type:confirmed bug
