### ISSUE TITLE
[Request] Add Active layer/Total layer to State box

### ISSUE THREAD

**Issue by toneknet** [foosel/OctoPrint#1368] opened 2016-06-09 09:25 UTC
Is it possible to add a line on the State message for Layer information as Active layer/Total layer?

**Comment by ntoff** [comment] 2016-06-09 09:30
Is this plugin of any use to you? http://plugins.octoprint.org/plugins/displayz/ Doesn't display the actual layer but the layer height. Be sure to read the notes on why it's not really that accurate though which may also apply to what you're asking.

**Comment by foosel** [comment] 2016-06-09 12:02
Duplicate of [soooo many similar issues](https://github.com/foosel/OctoPrint/search?q=total+layer&type=Issues&utf8=%E2%9C%93) (easily found with the search), see the reasons stated in those for why that won't be added to the core application.

**Closed by foosel** 2016-06-09 12:02 UTC
Labels: type:request
