### ISSUE TITLE
"Offline" MK2 - Logs included

### ISSUE THREAD

**Issue by Llama-Trauma** [foosel/OctoPrint#2153] opened 2017-10-17 00:16 UTC
I have read the FAQ

**Comment by Llama-Trauma** [comment] 2017-10-17 00:20
[octoprint.log](https://github.com/foosel/OctoPrint/files/1389364/octoprint.log)

Hoping someone can point me in the right direction for a new setup issue on a Pi Zero - I'm only getting the State "Offline" upon connection attempts.

Printer is connected to Pi Zero and powered on. (MK2)
Octoprint is loaded and connected to the Pi in my browser. - I can see my webcam when plugged in. 

A default Serial Port appeared after first connection, and I have tried that and AUTO, with AUTO baudrate as well as 250000.

Any help would be appreciated. 

Thank you!
Llama-Trauma

**Comment by ntoff** [comment] 2017-10-17 01:44
>IspError: 'Timeout'

Looks like a duplicate of https://github.com/foosel/OctoPrint/issues/2138

**Comment by foosel** [comment] 2017-10-17 08:25
Please provide _all_ requested information? Without that information this ticket cannot be looked into and will be closed. Thanks.

**Comment by Llama-Trauma** [comment] 2017-10-17 13:31
Go ahead and close it, I will look for support elsewhere. Too technical for me, just needed some advice :-)

Thanks

**Comment by foosel** [comment] 2017-10-17 13:37
From [here](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md):

> If you need **support**, have a **question** or some **other reason** that doesn't fit any of the above categories, the issue tracker is not the right place. Consult the [Mailinglist](https://groups.google.com/group/octoprint) or the [Google+ Community](https://plus.google.com/communities/102771308349328485741) instead.

**Closed by foosel** 2017-10-17 13:37 UTC
Labels: status:awaiting information
