### ISSUE TITLE
[Request] Saving GCode viewer settings

### ISSUE THREAD

**Issue by pixelk0** [foosel/OctoPrint#1769] opened 2017-02-12 10:46 UTC
#### What were you doing?

After oppening a tab with OctoPrint and uploading a gcode file

#### What did you expect to happen?

I'd like that the checkboxes I checked last time would still be checked and applied

#### What happened instead?

The checkboxes are reset to "Sync with job progress", "Show moves" and "Show retracts"

#### Branch & Commit or Version of OctoPrint

Version 1.3.1 (master branch)

#### Printer model & used firmware incl. version

CTC Prusa i3

#### Browser and Version of Browser, Operating System running Browser

Chrome 57, IE 11, Firefox 51 all gave the same result

#### Link to octoprint.log

http://pastebin.com/DV1ahybt

#### Screenshot(s) showing the problem:

http://stuff.knackes.com/dld/201702/ScreenCap-20170212-114524_A2954F7D.jpg

I have read the FAQ. Yes I did :)

**Comment by foosel** [comment] 2017-02-13 09:50
Duplicate of #443 :)

**Closed by foosel** 2017-02-13 09:50 UTC
Labels: type:request
