### ISSUE TITLE
[Request] Manual start of a timlapse video

### ISSUE THREAD

**Issue by mlkoch** [foosel/OctoPrint#705] opened 2015-01-04 10:01 UTC
I have not found a way to manually trigger a timelapse video.
I use a UM2 and always print using the printer's display-interface and sd-card.
Manually triggering a timlapse-video would be very helpful!

Best regards!
Michael

**Comment by smsagent** [comment] 2015-01-18 10:16
Hello,
I would like to add this feature too - while printing from SD card, only short still image of final print is made. It should be fine to have both options - timed and on Z axis change. I think, that OctoPi should read axis position while printing from SD card.

Regards!
Ondrej

**Comment by foosel** [comment] 2015-01-18 12:47
> I think, that OctoPi should read axis position while printing from SD card.

OctoPrint. OctoPi is the Raspberry Pi image. And no, it shouldn't. It would have to constantly query the data from the printer in order to achieve this and STILL would be off. That would lead to the printer firmware having to constantly answer queries (and hence risk slowing down processing) without adding real value. It just doesn't make sense to do that.

**Comment by mlkoch** [comment] 2015-01-18 16:07
I just thougt of a function to trigger the timlapse video by hand.
The trigger for the pictures needed for the video could be done by time (e.g. 120 sec.). Trigger by z-axis is not necessary.
That's all.
Best regards
Michael

**Comment by foosel** [comment] 2015-02-22 15:45
Duplicate of #452

**Closed by foosel** 2015-02-22 15:45 UTC
Labels: type:request
