### ISSUE TITLE
Octoprint Server Goes Offline Mid Print

### ISSUE THREAD

**Issue by darkseeker186** [foosel/OctoPrint#2680] opened 2018-06-13 05:26 UTC
#### What were you doing?

1. ...convert file to .gcode
2. ...upload to server (not SD card)
3. ... heat bed and extruder
4. ...click print
5. ...file prints about 50% and then message on webpage says octoprint server offline

#### Version of OctoPrint

OctoPrint 1.3.8

#### Operating System running OctoPrint

 running on OctoPi 0.15.0

#### Printer model & used firmware incl. version
Monoprice Maker Select V2

firmware-unsure

#### Browser and version of browser, operating system running browser

Chrome Version 66.0.3359.181 (Official Build) (64-bit)

#### Link to octoprint.log

https://www.dropbox.com/s/wwwchyu93ei8gdb/octoprint%20%281%29.log?dl=0

#### Link to contents of terminal tab or serial.log

https://www.dropbox.com/s/wwwchyu93ei8gdb/octoprint%20%281%29.log?dl=0

#### Link to contents of Javascript console in the browser

->

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.
[serial.log](https://github.com/foosel/OctoPrint/files/2096711/serial.log)
[octoprint (1).log](https://github.com/foosel/OctoPrint/files/2096712/octoprint.1.log)

**Comment by foosel** [comment] 2018-06-14 12:09
This looks very much like a duplicate of #2647. Please read through that and try out was suggested in there. Especially test if the problem persists in safe mode. Also check if just disabling/uninstalling OctoPrint Anywhere restores stability. The verdict is still out on whether that plugin is related to this kind of problem or not, but there's at least a correlation observable between people reporting crashed servers and the presence of that plugin.

**Closed by foosel** 2018-06-14 12:09 UTC
Labels: type:potential bug

**Comment by darkseeker186** [comment] 2018-06-16 03:51
Thanks so much. Sorry didn't realize it was a duplicate. I disabled the print anywhere plugin and it cleared it right up.
