### ISSUE TITLE
Can't login anymore, have TPLinkSmartplug Plugin installed

### ISSUE THREAD

**Issue by redsoxfn820** [foosel/OctoPrint#2170] opened 2017-10-23 05:03 UTC
**What were you doing?**
Using the login on the octoprint main web GUI page

**What did you expect to happen?**
The system to log me in and allow me to control my printer as usual.

**What happened instead?**
System thinks, then loads the octoprint GUI again and the url shows a login but the GUI will not enable controls and the tab still shows "Login" instead of "Logout" (See screenshot)

**Did the same happen when running OctoPrint in safe mode?**
Yes

**Branch & Commit or Version of OctoPrint**
OctoPrint 1.3.5 (master branch)

**Operating System running OctoPrint**
OctoP Jessie.

**Printer model & used firmware incl. version**
Prusa I3 w/ Repetier

**Browser and Version of Browser, Operating System running Browser**
Google Chrome Version 61.0.3163.100
Windows 10 Creators Update

**Screenshot(s)/video(s) showing the problem:**
![octoprint](https://user-images.githubusercontent.com/33015834/31872862-54a53b06-b78d-11e7-9f30-4172a7899770.png)

I have read the FAQ.

**Comment by ntoff** [comment] 2017-10-23 05:57
try to SSH in and `sudo service octoprint restart` and then ctrl + F5 in your browser 

also before anything can be looked into, you'll need to provide those logs that are requested, along with the javascript terminal in your browser.

**Comment by foosel** [comment] 2017-10-23 07:46
Please provide _all_ requested information. Without that information this ticket cannot be looked into and will be closed. Thanks.

**Comment by schnubbie** [comment] 2017-10-23 19:16
I had the same problem. I checked my logs and find out that the problem be caused by the TPSmartlink-Plugin. I unistalled it by ssh and now all is working fine again.

**Comment by jneilliii** [comment] 2017-10-23 21:20
I could use some help on this with my plugin.  I thought I had done the on_settings_migrate function correctly initially by setting a calue to null, but that didn't work, so I modified the latest branch, version 0.7.1 to set the setting to the equivalent defaults using self._settings.set(['arrSmartplugs'], self.get_settings_defaults().arrSmartplugs).  Please help @foosel.

**Comment by redsoxfn820** [comment] 2017-10-24 04:28
@schnubbie how did you uninstall it via ssh? what was the command?

**Comment by iceblu008** [comment] 2017-10-24 05:24
> @schnubbie how did you uninstall it via ssh? what was the command?

https://github.com/foosel/OctoPrint/wiki/FAQ#i-installed-a-broken-plugin-how-do-i-uninstall-it-again

**Comment by redsoxfn820** [comment] 2017-10-24 05:57
Thanks for the help @iceblu008 and @schnubbie uninstalling TPLinkSmartplug has solved the issue.

**Comment by foosel** [comment] 2017-10-24 07:27
@jneilliii I just pinged you on your own ticket on this.

**Comment by foosel** [comment] 2017-10-24 08:49
@redsoxfn820 if uninstalling that plugin indeed solved your issue, you posted some misleading information:

> **Did the same happen when running OctoPrint in safe mode?**
> Yes

It's ok to write that you couldn't try safe mode due to this issue, but if you'd really started OctoPrint in safe mode you'd not been able to reproduce this issue there - which is very very important information to debug stuff like that. So please, if you get asked to try something in safe mode and you can't, say you can't, not that you tried and the issue was still showing there too. 

In any case, this is a duplicate of #2168 and actually an issue with a third party plugin, not OctoPrint - see jneilliii/OctoPrint-TPLinkSmartplug#19. Since more people seem to run into this and 0.7.1 of the plugin also doesn't seem to solve this problem though, I'll leave this open for a bit so that people actually see it instead of opening new tickets about this all the time.

**Comment by BillyBlaze** [comment] 2017-10-24 10:26
@foosel , perhaps it's a good idea if we change event on the `<form>` of the post to something like this?: 

````
<form id="loginForm" data-bind="event: {'submit': loginState.prepareLogin }" onsubmit="return false;">
````

This to make sure we can prevent posting the page with GET even if knockout fails

**Comment by foosel** [comment] 2017-10-24 10:28
@BillyBlaze see 0f8f4579d6bf5afdaaa1217975fd02bbb2da49ee :D Already prepped for 1.3.6.

**Comment by BillyBlaze** [comment] 2017-10-24 10:29
You're awesome! 👍

**Comment by redsoxfn820** [comment] 2017-10-24 13:39
@foosel yes that was my fault, it was a copy paste error.  Sorry for the incorrect posting location as well!

Sounds good, Hopefully this will help others who installed the TPLinkSmartplug plugin

**Comment by jneilliii** [comment] 2017-10-24 18:14
Sorry for all the headaches guys...that's what I get for a being a hack programmer...lol.

**Comment by kantlivelong** [comment] 2017-11-30 18:21
Is this resolved? Can this ticket be closed?

**Comment by foosel** [comment] 2017-11-30 18:34
Hey, good point... it can!

**Closed by foosel** 2017-11-30 18:34 UTC
Labels: status:duplicate, type:not octoprint
