### ISSUE TITLE
Server not autoconnecting on startup if port is set to AUTO

### ISSUE THREAD

**Issue by ismangil** [foosel/OctoPrint#2311] opened 2017-12-21 18:43 UTC
#### What were you doing?

Ticked auto-connect on server startup

#### What did you expect to happen?

Server will connect to printer when server starts or restarted

#### What happened instead?

Server did not try to connect on startup 

#### Did the same happen when running OctoPrint in safe mode?

Yes. 

#### Version of OctoPrint

1.3.6

#### Operating System running OctoPrint

OctoPi 0.14.0

#### Printer model & used firmware incl. version

Marlin 1.1.4 GitHub

#### Browser and Version of Browser, Operating System running Browser

Any browser

#### Link to octoprint.log

https://gist.github.com/ismangil/6cf1e38e832b5d314f7961b371e7c166

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by 4325123** [comment] 2017-12-26 13:24
Just saying I have the same issue too.  I'm wondering if it has something to do with octoprint starting before the printer is being detected.

**Comment by kantlivelong** [comment] 2017-12-27 22:32
@ismangil can you provide fresh logs for both **octoprint.log** and **serial.log** with the issue occurring?

**Comment by ismangil** [comment] 2017-12-28 16:19
@kantlivelong Here it is: https://gist.github.com/ismangil/cc99d24ee982a04a2aba946609bf2cdf

Note the serial.log is only generated once I manually click ```Connect```, because the server is not auto-connecting.

**Comment by kantlivelong** [comment] 2017-12-28 16:43
Yeah not much of use there as far as I can tell. If you login to SSH and run `cat /var/log/syslog | grep kernel | grep -A5 -B5 "tty"` you should see when the serial device was detected by the kernel. Does it show up before OctoPrint starts?

**Comment by ismangil** [comment] 2017-12-28 17:37
@kantlivelong you may have something there. If I I'm looking at the log correctly, OctoPrint may be starting up before /dev/ttyUSB0 become available. I suppose in this case it's an OctoPi configuration issue on how to wait a bit or detect ttyUSB0.

**Comment by kantlivelong** [comment] 2017-12-28 17:41
The [PortLister](https://plugins.octoprint.org/plugins/portlister) plugin should work as a workaround. I personally use it as it also will reconnect after resetting the printer controller.

**Comment by ismangil** [comment] 2017-12-28 17:46
@kantlivelong however, that doesn't explain why it doesn't connect on server restart (not a reboot) doesn't it? The port is already there, yet OctoPrint is still not autoconnecting.

**Comment by kantlivelong** [comment] 2017-12-28 17:53
Hmm...

What's the make and model of printer/controller are you using?

**Comment by ismangil** [comment] 2017-12-28 17:57
MKS GEN L 1.0

**Comment by ismangil** [comment] 2018-01-01 00:53
I've found the cause: If port is left on `AUTO` then

`if port in connectionOptions["ports"]:`

fails, because `AUTO` is not on the list of ports.

Yet when I click connect, it's able to connect. So the solution seems the autoconnect logic needs to follow the manual button logic.

For my current use, if I specify the specific port, then it can autoconnect just fine.

I've updated the issue title.

**Comment by kantlivelong** [comment] 2018-01-03 04:39
Well that's interesting... I've confirmed your findings here as well.

**Comment by kantlivelong** [comment] 2018-01-03 05:15
Hi @ismangi,

I've submitted a PR that fixes this.

**Comment by jneilliii** [comment] 2018-01-03 09:42
Does this also effect the Virtual Printer port?  I can never seem to get that one to autoconnect when testing my plugins.

**Comment by kantlivelong** [comment] 2018-01-03 14:47
@jneilliii only if you had the serial port set to AUTO.

**Comment by jneilliii** [comment] 2018-04-08 00:45
I just tested against 1.3.7rc4 and the behavior is still the same for me with VIRTUAL serial port, and the option selected as AUTO.  This is the output in the terminal.

Changing monitoring state from "Offline" to "Detecting serial port"
Serial port list: ['VIRTUAL']
Connecting to: VIRTUAL
Changing monitoring state from "Detecting serial port" to "Error: Connection error, see Terminal tab"
Unexpected error while connecting to serial port: AUTO OSError: '[Errno 2] No such file or directory: 'VIRTUAL'' @ comm.py:_openSerial:2304 (hook default)

**Comment by foosel** [comment] 2018-04-09 07:50
`VIRTUAL` doesn't and has never supported auto detection, so this is expected behaviour.

**Comment by foosel** [comment] 2018-04-09 15:13
Closing as 1.3.7 was just released.

**Closed by foosel** 2018-04-09 15:13 UTC
Labels: status:solved, type:confirmed bug

**Comment by nickm324** [comment] 2019-01-13 20:16
This issue still exists in 1.3.10.

**Comment by foosel** [comment] 2019-01-14 09:12
@nickm324 then please fill out the ticket template so this can be looked into

**Comment by Edo78** [comment] 2019-01-21 21:16
I'm experiencing the very same issue, even in safe mode. I'm on OctoPrint 1.3.10 running on OctoPi 0.15.1

It's not a big deal since I set the right value and now I'm autoconnecting but it's stilla bug ... do you want me to create a new issue for this bug?

**Comment by seltix5** [comment] 2019-08-26 12:37
Hello,
I have the same problem. Is there already a new issue created for this bug sinse this one is closed?

**Comment by foosel** [comment] 2019-09-04 08:04
Please open a new ticket.

**Comment by seltix5** [comment] 2019-09-08 18:47
new issue created https://github.com/foosel/OctoPrint/issues/3267
