### ISSUE TITLE
Cura Profile Import Error

### ISSUE THREAD

**Issue by quillford** [foosel/OctoPrint#878] opened 2015-04-28 23:20 UTC
1. What were you doing? Importing a Cura profile for slicing within OctoPrint

2. What did you expect to happen? The profile to import

3. What happened instead? Error (400 Bad reqeust)

4. Branch & Commit or Version of OctoPrint: 1.2.0-dev-705-ga34cbc5 (devel branch)

5. Printer model & used firmware incl. version
   (if applicable - always include if unsure): irrelevant

6. Browser and Version of Browser, Operating 
   System running Browser (if applicable - always 
   include if unsure): Chrome 42.0.2311.90 (Official Build) (64-bit)

7. Link to octoprint.log on gist.github.com or pastebin.com
   (ALWAYS INCLUDE AND DO NOT TRUNCATE): [octoprint.log](https://gist.github.com/quillford/5c10c5ca776be195adc4)

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure or reporting communication issues AND
   DO NOT TRUNCATE):

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues): http://hastebin.com/nujoqezewa.hs

10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues): ![prusa_i3_polygoose__octoprint__and_quillford_on_freenode_irc_network_ __reprap__535_users_](https://cloud.githubusercontent.com/assets/8762862/7382322/53b5eba6-edc2-11e4-87fd-86b580aa0d37.png)

I have read the FAQ.

**Comment by foosel** [comment] 2015-05-04 09:31
Can you please provide the profile with which you are experiencing these problems? Thanks

**Comment by quillford** [comment] 2015-05-07 03:56
http://hastebin.com/xacenimozi.avrasm

**Comment by foosel** [comment] 2015-05-07 08:16
Somehow I'm really lucky these days when it comes to bugs I can't reproduce it seems... Rolled back to your version, tried importing your profile, worked flawlessly :/ I first thought it might be an old bug I thought I'd fixed that caused importing not to work when the path to the CuraEngine binary was not set, but when I removed that I still could import just fine, so it's not that.

I'll try the following: I'll add some more validation logging to the cura plugin. That should then at least give us a hint why your profile can't import. It would be great if you would also update to the current devel so we can be sure the problem still persists there (probably, since if it's happening for you on 705 and not for me, chances are high it's still happening for you on the current HEAD although it's not happening for me, haven't touched the plugin in a while).

**Comment by foosel** [comment] 2015-05-08 12:05
@quillford I added more logging, can you update and report if a) the issue still persist or not and b) if it still persists provide another log (this time it should hopefully include more helpful information after the commit above).

**Comment by markwal** [comment] 2015-05-08 17:02
Perhaps version of CuraEngine is relevant?

**Comment by foosel** [comment] 2015-05-09 22:58
No, CuraEngine isn't involved in the profile management part, that only gets active once you actually want to slice something.

**Comment by foosel** [comment] 2015-05-09 23:01
On closer look, that actually looks like a duplicate of #795. Closing this for now (please correct me if I'm mistaken in assuming this to be the same, symptoms sound identical), but @quillford please provide information as requested above!

**Closed by foosel** 2015-05-09 23:01 UTC
Labels: status:awaiting information

**Comment by quillford** [comment] 2015-05-09 23:04
Sorry. The printer I use slicing within OctoPrint is down. I'll try it right now. But that issue seems similar.
