### ISSUE TITLE
[request] Timelapse =>  FFMPEG during print

### ISSUE THREAD

**Issue by Loup911** [foosel/OctoPrint#1205] opened 2016-01-31 07:15 UTC
I noticed that if I start a new printing before the convertion of the video file is complete the file was not completely generate.

Is it possible you to create temporary folder containing the image and when the video is complete the temporary directory is simply remove.

**Comment by foosel** [comment] 2016-01-31 08:17
Duplicate of #318 (found by simply searching for "timelapse")

**Closed by foosel** 2016-01-31 08:17 UTC
Labels: type:request
