### ISSUE TITLE
[Request] Ability to add notes from the web interface on files printed

### ISSUE THREAD

**Issue by NemesisDude** [foosel/OctoPrint#2384] opened 2018-01-25 22:18 UTC
Ability to add notes from the web interface on files printed.
In a tab or within the file list dropdown?

It would be helpful for myself as well as others I think to have a central place for notes on prints, especially when they fail so it's easier to track changes to the gcode and such, also for the successful prints 

Thank you Thank You Thank you!!! I can't say it enough for the time and effort you have put in to this it is a work of art!!
I hope to contribute in some way someday.
Thanks Again
Glen

OctoPrint 1.3.6 running on OctoPi 0.14.0
I have read the FAQ.

**Comment by ntoff** [comment] 2018-01-26 11:19
more or less a duplicate of https://github.com/foosel/OctoPrint/issues/519

**Comment by foosel** [comment] 2018-02-12 09:49
Agreed, closing as duplicate.

**Closed by foosel** 2018-02-12 09:49 UTC
Labels: type:request
