### ISSUE TITLE
Print aborted with error message from Marlin "Error:No Checksum with line number"

### ISSUE THREAD

**Issue by sprior** [foosel/OctoPrint#490] opened 2014-06-05 19:12 UTC
I'm running:
pi@m2 ~/OctoPrint $ git log
commit 244128c7ed617512a5982cddae232bb87fc61377
Merge: 9c9b98d 7bba1dc
Author: Gina Häußge <osd@foosel.net>
Date:   Sun May 25 20:19:03 2014 +0200

I was in the middle of printing something and the print suddenly stopped for no apparent reason. I use a Raspberry Pi running Octoprint to control the printer, but it's not obvious whether it's the gcode, Octoprint, or firmware to blame. Here's the log.

Send: N6429 G1 X41.025 Y245.824 E3.5575*85
Recv: ok
Send: M105
Recv: ok
Send: N6430 G1 X41.857 Y246.406 E3.6066*91
Recv: ok
Send: N6431 G1 X53.331 Y234.932 E4.3909*95
Recv: Error:No Checksum with line number, Last Line:6428
Recv: Resend:6429
Send: N6429 G1 X41.025 Y245.824 E3.5575*85
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line:6428
Recv: Resend:6429
Send: N6429 G1 X41.025 Y245.824 E3.5575*85
Recv: ok
Recv: ok
Send: N6430 G1 X41.857 Y246.406 E3.6066*91
Recv: Error:Line Number is not Last Line Number+1, Last Line:6429
Recv: Resend:6430
Send: N6430 G1 X41.857 Y246.406 E3.6066*91
Recv: ok
Recv: ok
Send: N6431 G1 X53.331 Y234.932 E4.3909*95
Recv: Error:Line Number is not Last Line Number+1, Last Line:6430
Recv: Resend:6431
Send: N6431 G1 X53.331 Y234.932 E4.3909*95
Recv: ok
Recv: ok
Send: M105
Recv: Error:Line Number is not Last Line Number+1, Last Line:6431
Recv: Resend:6432
Changing monitoring state from 'Printing' to 'Error: Printer requested li...'
Recv: ok

**Comment by foosel** [comment] 2015-03-03 09:42
Please test if that still occurs with current ``devel``

**Comment by thaytan** [comment] 2015-04-16 13:32
I'm getting similar looking errors with current git master, with 'swallow first OK after resend' enabled:

Send: N55 G1 X70.590 Y105.806 E3.30715*96
Recv: ok
Send: N56 G1 X70.798 Y106.145 E3.32160*98
Recv: ok
Send: N57 G1 X71.083 Y106.833 E3.34864*108
Recv: Error:No Line Number with checksum, Last Line: 56
Communication timeout during printing, forcing a line
Send: N58 M105*26
Recv: echo:Unknown command: ""
Recv: ok
Send: N59 M105*27
Recv: Error:No Line Number with checksum, Last Line: 56
Communication timeout during printing, forcing a line
Send: N60 M105*17
Recv: echo:Unknown command: ""
Recv: ok
Send: N61 M105*16
Recv: Error:No Line Number with checksum, Last Line: 56
Communication timeout during printing, forcing a line
Send: N62 M105*19
Recv: echo:Unknown command: ""
Recv: ok
Send: N63 M105*18
Recv: Error:Line Number is not Last Line Number+1, Last Line: 56
Recv: Resend: 57
Send: N57 G1 X71.083 Y106.833 E3.34864*108
Recv: ok

**Comment by foosel** [comment] 2015-04-16 13:38
@thaytan I took the liberty to format your log to make it more readable. That looks like a valid communication problem to me. The "No Line Number with checksum" implicates that your printer did not receive the `N57` part in `N57 G1 X71.083 Y106.833 E3.34864*108`. The several `echo:Unknown command: ""` in there also make me suggest to check your cables. Something's going wrong there that's not caused by software (at least not on the sending side).

**Comment by thaytan** [comment] 2015-04-16 13:42
Switching to a different USB port and moving the USB cable seems to work better indeed.

**Comment by foosel** [comment] 2015-06-03 11:27
Closing since assuming this is now fixed by the extensive changes in the comm layer (no feedback, no choice)

**Closed by foosel** 2015-06-03 11:27 UTC
Labels: epic:commRefactoring, status:awaiting information

**Comment by d00616** [comment] 2015-09-13 08:49
I'm not the opener of this issue but i had the same problem. After updating this was solved for me. Thanks.

**Comment by FormerLurker** [comment] 2018-01-18 22:02
I'm getting a similar lockup.  Here is my log:

Recv: ok
Send: N90930 G1 X130.525 Y110.956 E0.01892*105
Recv: Error:No Checksum with line number, Last Line: 90928
Recv: Resend: 90929
Recv: Error:Line Number is not Last Line Number+1, Last Line: 90928
Recv: Resend: 90929
Communication timeout during an active resend, resending same line again to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: N90928 G1 X130.950 Y110.281 E0.01077*108
Recv: Error:Line Number is not Last Line Number+1, Last Line: 90928
Recv: Resend: 90929

I've been developing a plugin, and I thought it might be causing problems, but I uninstalled it, rebooted and got the same issue at a different point during my print.  Any ideas?

**Comment by foosel** [comment] 2018-01-18 22:15
Original Prusa? See #2285 and prusa3d/Prusa-Firmware#331. In any case a firmware issue (your firmware is missing an ok after the resend request). Workaround for that firmware bug is available and described in both of the tickets linked above.

**Comment by FormerLurker** [comment] 2018-01-18 23:51
You are 100% correct.  I investigated the logs and see the same problem you have discovered.  I'm SO glad it's not my plugin (or your wonderful print server).  Also, thank you for being so responsive!

**Comment by hoegge** [comment] 2018-01-28 21:16
The workaround does not seem to work in my case (octoprint 1.3.6. on octopi 0.14, Prusa i3 MK2s, FW: 2.13)

```
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39686
Recv: Resend: 39687
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39686
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39687
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39687
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39687
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39687
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39687
Recv: Resend: 39688
Recv: ok
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39688
Recv: Resend: 39689
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39688
Recv: Resend: 39689
Recv: ok
Recv: echo:Unknown command: "83"
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39688
Recv: Resend: 39689
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39688
Recv: Resend: 39689
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39688
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Full RX Buffer
Recv: Error:No Line Number with checksum, Last Line: 39689
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39689
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39689
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 39689
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Recv: ok
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:No Line Number with checksum, Last Line: 39689
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Resend: 39690
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: ok
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39Error:Line Number is not Last Line Number+1, Last Line: 39689
Printer requested line 39 but no sufficient history is available, can't resend
Changing monitoring state from 'Printing' to 'Error: Printer requested line 39 but no sufficient history is available, can't resend'
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Recv: Resend: 39690
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: ok
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:No Line Number with checksum, Last Line: 39689
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39689
Recv: Resend: 39690
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Recv: ok
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: ok
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:No Line Number with checksum, Last Line: 39690
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:No Line Number with checksum, Last Line: 39690
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39687 G1 X115.397 Y94.832 E0.00676*90
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39688 G1 X115.130 Y94.524 E0.00672*84
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39689 G1 X114.838 Y94.239 E0.00672*94
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Send: N39690 G1 X114.523 Y93.976 E0.00676*82
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691
Recv: Error:Line Number is not Last Line Number+1, Last Line: 39690
Recv: Resend: 39691```

**Comment by FormerLurker** [comment] 2018-01-28 22:56
@hoegge, slice without the 'Linear Advance' profile and turn the workaround you were using off.  I've had the most success that way  myself.  Not sure if it's necessary, but I also changed the Filament Settings->Custom G-Code to: M900 K0

**Comment by tcurdt** [comment] 2018-01-28 23:05
@FormerLurker not sure why one would consider changing the "Linear Advance" on the slicing on this issue. That does not make much sense to me at all.

**Comment by FormerLurker** [comment] 2018-01-28 23:48
Odd isn't it.  It seems as though linear advances taxes the CPU and causes serial issues on the mk2 and mk3 using the latest firmware.  See: https://github.com/prusa3d/Prusa-Firmware/issues/331
