### ISSUE TITLE
Not able to update in Web UI

### ISSUE THREAD

**Issue by Tenderfoot14** [foosel/OctoPrint#1621] opened 2016-12-04 20:52 UTC
#### What were you doing?

I opened octoprint and saw an update was available.

#### What did you expect to happen?

I would update octoprint through the softwareupdate dialog.

#### What happened instead?

Every time (this has happened for multiple versions) there is an update, I am not able to update it from the web ui.

#### Branch & Commit or Version of OctoPrint

Version: 1.2.17 (master branch)

#### Printer model & used firmware incl. version

Printrbot Simple Metal

#### Browser and Version of Browser, Operating System running Browser

Safari, MacOS sierra

#### Link to octoprint.log

http://pastebin.com/hftuSMdF

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s) showing the problem:

<img width="509" alt="screen shot 2016-12-04 at 3 51 05 pm" src="https://cloud.githubusercontent.com/assets/3798059/20869106/8930d544-ba39-11e6-9913-c78d1e7013d5.png">

I have read the FAQ.

**Comment by gege2b** [comment] 2016-12-05 08:41
It's not exactly the same error, but it seems to be related to #1586 (unicode stuff messing with the upgrade)

If it's the case, it should already be fixed in 1.3.0

**Comment by foosel** [comment] 2016-12-05 10:41
The little x next to the update information hints at some misconfiguration being the reason here. Usually that is the case if you haven't configured OctoPrint's checkout folder. If you open up Settings > Software Update, is there a yellow warning message and an exclamation mark next to OctoPrint?

![image](https://cloud.githubusercontent.com/assets/83657/20882106/a51a2368-badf-11e6-862b-9b141afeb13b.png)

How does the plugin configuration (click the little wrench icon) look like, especially the configured folder?

![image](https://cloud.githubusercontent.com/assets/83657/20881881/b3473468-bade-11e6-84f0-7696635375af.png)

The above is what it should look like under OctoPi for things to properly work.

@gege2b The issue here looks differently - your's was running into trouble during the update itself. This here is a case of the "Update Now" button not even being available due to OctoPrint not having (or thinking to not have) all required information to even perform the update.

**Comment by Tenderfoot14** [comment] 2016-12-06 00:32
There were no errors for lack of a checkout directory, but the directory did not exist. Here is my former plugin config:
<img width="579" alt="screen shot 2016-12-05 at 7 26 55 pm" src="https://cloud.githubusercontent.com/assets/3798059/20908188/12faf9b6-bb21-11e6-911f-7b2e1b9fc91f.png">

I updated the directory to one on my external drive, and made that directory.
<img width="573" alt="screen shot 2016-12-05 at 7 26 35 pm" src="https://cloud.githubusercontent.com/assets/3798059/20908197/2ed4e052-bb21-11e6-8f86-3161fcf52c09.png">

I restarted the octoprint service, but still no dice. It's also worth noting that I am running Octoprint on a Pi, but not running the OctoPi image.

**Comment by Kunsi** [comment] 2016-12-09 09:16
Checkout directory should be directory where OctoPrint is located. Also should be writeable by OctoPrint-User.

**Comment by foosel** [comment] 2016-12-09 09:37
@Tenderfoot14 How exactly did you install OctoPrint? Are you using OctoPi? If not, what exactly did you do to initially get OctoPrint up and running?

The checkout folder definitely needs to *already exist*, it's not something you can freely configure and then stuff works but the correct value you need to put there depends on how you initially setup OctoPrint. On OctoPi the correct one is `/home/pi/OctoPrint` (and it ships with that preconfigured). If you are running OctoPi and that directory did not exist anymore, something seriously broke in your OctoPi installation.

Finally, this is a support issue, not a bug. Since we already started discussion here let's keep tracking this done here, but in the future with issues like these please use the mailing list or the g+ community because those are the actual support channels. This is a bug tracker reserved for actual bugs in the software.

**Comment by foosel** [comment] 2017-01-27 18:07
Well, apparently we are not handling this here since OP doesn't respond anymore. Closing.

**Closed by foosel** 2017-01-27 18:07 UTC
Labels: status:awaiting information
