### ISSUE TITLE
Error message ends with %(error)s instead of actual error message

### ISSUE THREAD

**Issue by dforsi** [foosel/OctoPrint#2499] opened 2018-03-20 16:04 UTC
#### What were you doing?

I was using the Connect and Disconnect buttons in the main window.

I'm not able to reproduce this problem but I see that some usages of `gettext()` in `dataupdater.js` use `sprintf()` and some don't.

#### What did you expect to happen?

A human friendly message is shown.

#### What happened instead?

The literal string `%(error)s` is shown.

#### Version of OctoPrint

1.3.7rc1

#### Printer model & used firmware incl. version

No printer.

#### Link to contents of terminal tab or serial.log

serial.log wasn't enabled

#### Screenshot(s)/video(s) showing the problem:

![unknown error](https://user-images.githubusercontent.com/1055635/37665532-c6d12254-2c5d-11e8-9383-aa3c3c3c72e7.png)

I have read the FAQ.

**Comment by kantlivelong** [comment] 2018-03-20 16:18
@dforsi 

Can you attach the octoprint.log file?

**Comment by dforsi** [comment] 2018-03-20 18:53
I found this log which is the only one showing something about serial (I did a search and replace for the duplicated SlicerNotConfigured exceptions after the first one).
https://pastebin.com/h1mm8GkW

Note that I had edited config.yaml to put the non-numeric value "foo" as baudrate and I have a temperature sensor on /dev/ttyUSB0 that is sending ASCII text lines such as
> mar 19 19:29:18 raw: 84 90mV 8% 9 C

**Comment by foosel** [comment] 2018-03-20 19:16
Well, at least the pip error appears to be caused by pip 9.0.2: https://github.com/pypa/pip/issues/5079

And it looks like once again I have to find a way to figure something out about pip without spawning a subprocess, because for some reason imports are discouraged and what feels like outright sabotaged.

**Comment by foosel** [comment] 2018-03-23 09:09
Forgot to mention: fixed in what will be 1.3.7rc2

**Comment by foosel** [comment] 2018-03-23 16:32
1.3.7rc2 was released earlier today which should fix this issue.

**Closed by foosel** 2018-03-23 16:32 UTC
Labels: status:solved, type:confirmed bug
