### ISSUE TITLE
[Feature Request] Folders of files?

### ISSUE THREAD

**Issue by jaygrovr** [foosel/OctoPrint#552] opened 2014-08-14 23:50 UTC
Would be cool to be able to store gcode in folders and manipulate them easily from the web interface.  Move to folder, create folder and so forth.  Also make some automatic filters, uploaded date, last printed, quantity printed?

Jason

**Comment by foosel** [comment] 2015-03-23 12:17
Also duplicate of #31

**Closed by foosel** 2015-03-23 12:17 UTC
Labels: type:request
