### ISSUE TITLE
Too many consecutive timeouts

### ISSUE THREAD

**Issue by purist69** [foosel/OctoPrint#2833] opened 2018-10-03 02:40 UTC
This issue happens on two separate board, a Raspberry Pi Model 3B+ with the 0.15.1 image installed and a custom install on a Rock64 with DietPi.  Both work fine with my i3 clone.

#### What were you doing?

1. Load web interface
2. Click 'Connect'
3. Wait 2-3 minutes

#### What did you expect to happen?

Successfully connect without error

#### What happened instead?

The following error popped up:

Communication error
There was a communication error while talking to your printer. Please consult the terminal output and octoprint.log for details. Error: Too many consecutive timeouts, printer still connected and alive?

#### Did the same happen when running OctoPrint in safe mode?

yes

#### Version of OctoPrint

1.39

#### Operating System running OctoPrint

official octopi image 0.15.1 running on a RPi 3B+ AND
DietPi 6.16 on Rock64

#### Printer model & used firmware incl. version

Prusa i3 MK3 with firmware 3.4.0-1327

#### Browser and version of browser, operating system running browser

Chrome 69 on Windows 10

#### Link to octoprint.log

```
2018-10-03 02:31:23,558 - octoprint.startup - INFO - ******************************************************************************
2018-10-03 02:31:23,560 - octoprint.startup - INFO - Starting OctoPrint 1.3.9
2018-10-03 02:31:23,561 - octoprint.startup - INFO - ******************************************************************************
2018-10-03 02:31:23,631 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2018-10-03 02:31:23,633 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-10-03 02:31:25,463 - octoprint.plugin.core - INFO - Found 21 plugin(s) providing 21 mixin implementations, 19 hook handlers
2018-10-03 02:31:25,560 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2018-10-03 02:31:25,587 - octoprint.server - INFO - Intermediary server started
2018-10-03 02:31:25,588 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-10-03 02:31:26,193 - octoprint.plugin.core - INFO - Found 21 plugin(s) providing 21 mixin implementations, 19 hook handlers
2018-10-03 02:31:26,230 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2018-10-03 02:31:26,879 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2018-10-03 02:31:27,092 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2018-10-03 02:31:28,928 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-10-03 02:31:30,757 - octoprint.util.pip - INFO - Version of pip is 9.0.3
2018-10-03 02:31:30,759 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-10-03 02:31:30,760 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-10-03 02:31:30,765 - octoprint.plugin.core - INFO - Initialized 21 plugin implementation(s)
2018-10-03 02:31:30,776 - octoprint.plugin.core - INFO - 21 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Display ETA (1.0.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eta
|  DisplayZ (0.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_displayz
|  FileManager (0.1.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filemanager
|  Fullscreen Plugin (0.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_fullscreen
|  LayerDisplay (0.4.1) = /home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  MultipleUpload Plugin (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_MultipleUpload
|  OctoPi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/octopi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Print History Plugin (1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Printer Stats (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stats
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Tempsgraph Plugin (0.3.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tempsgraph
|  TouchUI (0.3.12) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
2018-10-03 02:31:30,794 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1400.0
|    ram: 918192128
|  os:
|    id: linux
|    platform: linux2
|  plugins:
|    octopi_support:
|      model: unknown
|      revision: a020d3
|      version: 0.15.1
|  python:
|    pip: 9.0.3
|    version: 2.7.13
|    virtualenv: /home/pi/oprint
2018-10-03 02:31:30,806 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2018-10-03 02:31:30,825 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2018-10-03 02:31:31,022 - octoprint.server - INFO - Shutting down intermediary server...
2018-10-03 02:31:31,457 - octoprint.server - INFO - Intermediary server shut down
2018-10-03 02:31:31,460 - octoprint.events - INFO - Processing startup event, this is our first event
2018-10-03 02:31:31,461 - octoprint.events - INFO - Adding 1 events to queue that were held back before startup event
2018-10-03 02:31:31,489 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2018-10-03 02:31:31,500 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2018-10-03 02:31:31,513 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-10-03 02:31:31,755 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-10-03 02:31:31,762 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for _http._tcp
2018-10-03 02:31:31,846 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for _octoprint._tcp
2018-10-03 02:31:31,892 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2018-10-03 02:31:31,897 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2018-10-03 02:31:32,119 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-10-03 02:31:32,475 - octoprint.plugins.stats - INFO - Printer Stats
2018-10-03 02:31:32,627 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-10-03 02:31:32,718 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.137
2018-10-03 02:31:33,202 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.168/'}
2018-10-03 02:31:37,743 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial port"
2018-10-03 02:31:38,202 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial port" to "Opening serial port"
2018-10-03 02:31:38,264 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Detecting baudrate"
2018-10-03 02:31:39,480 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-10-03 02:31:39,494 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting baudrate" to "Operational"
2018-10-03 02:31:39,731 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-10-03 02:31:46,274 - octoprint.server.preemptive_cache - INFO - ... done in 13.07s
2018-10-03 02:32:09,717 - octoprint.util.comm - INFO - Communication timeout while idle, trying to trigger response from printer.
2018-10-03 02:32:39,757 - octoprint.util.comm - INFO - Communication timeout while idle, trying to trigger response from printer.
2018-10-03 02:33:09,796 - octoprint.util.comm - INFO - No response from printer after 3 consecutive communication timeouts, considering it dead.
2018-10-03 02:33:09,807 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline (Error: Too many consecutive timeouts, printer still connected and alive?)"
```

#### Link to contents of terminal tab or serial.log

```
2018-10-03 02:31:37,717 - serial.log is currently not enabled, you can enable it via Settings > Serial Connection > Log communication to serial.log
2018-10-03 02:35:39,988 - Enabling serial logging
2018-10-03 02:35:44,194 - Changing monitoring state from "Offline" to "Detecting serial port"
2018-10-03 02:35:44,215 - Serial port list: ['/dev/ttyACM0']
2018-10-03 02:35:44,215 - Connecting to: /dev/ttyACM0
2018-10-03 02:35:44,229 - Changing monitoring state from "Detecting serial port" to "Opening serial port"
2018-10-03 02:35:44,232 - Connected to: Serial<id=0x6db69350, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
2018-10-03 02:35:44,232 - Starting baud rate detection...
2018-10-03 02:35:44,233 - Changing monitoring state from "Opening serial port" to "Detecting baudrate"
2018-10-03 02:35:45,238 - Trying baudrate: 115200
2018-10-03 02:35:45,244 - Send: N0 M110 N0*125
2018-10-03 02:35:45,353 - Recv: start
2018-10-03 02:35:45,355 - Changing monitoring state from "Detecting baudrate" to "Operational"
2018-10-03 02:35:45,368 - Send: N0 M110 N0*125
2018-10-03 02:36:15,395 - Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
2018-10-03 02:36:15,404 - Send: N1 M115*39
2018-10-03 02:36:45,434 - Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
2018-10-03 02:36:45,444 - Send: N2 M21*18
2018-10-03 02:37:15,473 - No response from printer after 3 consecutive communication timeouts, considering it dead. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
2018-10-03 02:37:15,485 - Changing monitoring state from "Operational" to "Offline (Error: Too many consecutive timeouts, printer still connected and alive?)"
2018-10-03 02:37:15,495 - Connection closed, closing down monitor
```

#### Link to contents of Javascript console in the browser

I dont know how to get this

#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/34849863/46387308-fdbafd00-c67a-11e8-9dcf-81c06be901f9.png)

I have read the FAQ.

*edit by @foosel: fix formatting*

**Comment by bolsoncerrado** [comment] 2018-10-15 08:57
https://github.com/foosel/OctoPrint/issues/2843#issuecomment-429759157 ?

**Comment by foosel** [comment] 2018-10-15 09:01
Indeed looks like a duplicate of #2843 - and a firmware bug, not OctoPrint.

**Closed by foosel** 2018-10-15 09:01 UTC
Labels: type:potential bug
