### ISSUE TITLE
[Request]  Allow saving of GCode Viewer Render Options

### ISSUE THREAD

**Issue by dlbyers** [foosel/OctoPrint#843] opened 2015-04-09 19:35 UTC
Each time I start a new printing session and go to GCode Viewer, I always check the same boxes "Center on model", "Also show previous layer".  It would be a nice feature if OctoPrint remembered these preferences so that I don't have to select them each time.  

BTW - I LOVE OctoPrint!

**Comment by foosel** [comment] 2015-04-13 16:17
Duplicate of #443

**Closed by foosel** 2015-04-13 16:17 UTC
Labels: type:request
