### ISSUE TITLE
[Request] Drop-box "After print perform [shutdown/turn printer off/none] in print section GUI

### ISSUE THREAD

**Issue by GHPS** [foosel/OctoPrint#630] opened 2014-10-23 20:19 UTC
The remote power control of the printer via relay is a feature which one wouldn't miss again after a single day of use. In the morning I boot up the raspberry pi and turn on the printer whenever I need it with the commands of the systems menu.

Unfortunately the power off is a bit awkward. I can setup a generic power off event which turns off the printer after each job. Or I wait and do it manually. Especially at night - when a job takes longer than expected - not very comfortable.

So the idea lies at hand to use a feature every CD burning tool has implemented today: A simple checkmark or dropbox to shutdown the machine when the job is finished. In OctoPrint this could be located beneath the print/pause/cancel buttons so that the user can decide what to do even after he has already started the job. 

IMO easy to implement and powerful in practice.

**Comment by bolsoncerrado** [comment] 2015-02-22 14:39
...and any chances to add a "email me" alert or something like that once the print finishes?

**Comment by foosel** [comment] 2015-02-22 14:46
@bolsoncerrado https://github.com/foosel/OctoPrint/wiki/Cookbook:-Useful-Eventhooks

**Comment by foosel** [comment] 2015-03-23 12:35
Duplicate of #283

**Closed by foosel** 2015-03-23 12:35 UTC
Labels: type:request
