### ISSUE TITLE
High processor load

### ISSUE THREAD

**Issue by RobotCaleb** [foosel/OctoPrint#390] opened 2014-02-23 04:22 UTC
I'm printing a vased rocket ship. That is, no infill, spiral walls. It looks like a pile of warts due to the printer stalling and staying in one spot for long periods (seconds). I suspect it's due to communication issues caused by extremely high system load.

I am running 2014-01-07-wheezy-octopi-0.8.0.zip and had just restarted the RPI before this print. There are no people connected to the web interface while this is occurring.

Top shows:
```
top - 21:16:50 up  1:39,  1 user,  load average: 136.97, 118.25, 93.16
Tasks:  70 total,   1 running,  69 sleeping,   0 stopped,   0 zombie
%Cpu(s): 71.5 us, 24.4 sy,  0.0 ni,  0.0 id,  1.9 wa,  0.0 hi,  2.2 si,  0.0 st
KiB Mem:    123360 total,   111092 used,    12268 free,     3068 buffers
KiB Swap:   102396 total,    20412 used,    81984 free,    47448 cached

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND                                                      
 2154 pi        20   0 1281m  18m 1504 S  77.7 15.3  48:21.41 python                                                       
   39 root      20   0     0    0    0 S  10.4  0.0   2:24.83 mmcqd/0                                                      
 2171 pi        20   0 64784 3340 2776 S   5.9  2.7   5:03.52 mjpg_streamer                                                
22751 pi        20   0  4628  740  484 R   2.0  0.6   0:59.31 top                                                          
    3 root      20   0     0    0    0 S   0.7  0.0   0:37.53 ksoftirqd/0                                                  
    7 root      20   0     0    0    0 S   0.7  0.0   0:30.71 rcu_preempt                                                  
   13 root      20   0     0    0    0 S   0.7  0.0   0:19.38 kworker/0:1                                                  
 1862 root      20   0 27932  808  496 S   0.7  0.7   0:40.97 rsyslogd                                                     
 2191 pi        20   0  9436  468  344 S   0.7  0.4   0:16.91 sshd                                                         
    1 root      20   0  2100  248  228 S   0.0  0.2   0:02.08 init                                                         
    2 root      20   0     0    0    0 S   0.0  0.0   0:00.01 kthreadd       
```

![img_20140222_211027](https://f.cloud.github.com/assets/113401/2239595/c1c46c54-9c41-11e3-9b80-ce239ca8f816.jpg)

**Comment by foosel** [comment] 2015-03-23 12:24
Since there have been a lot of changes on the comm layer since this was first opened and it also has already been pointed out that high load due to other processes than OctoPrint can and will negatively influence print quality, I'm closing this now.

If the issue still persists with the current `devel` branch (and its changed comm layer) and is definitely caused by OctoPrint itself (as in, high load on that process), not any 3rd party apps on the same machine, feel free to create a new ticket.

**Closed by foosel** 2015-03-23 12:24 UTC
Labels: status:investigating

**Comment by jrsprice** [comment] 2016-04-29 22:15
I'm running raspberry pi 3 and ran into this on the 2nd of the 3 prints (same gcode). The first print was perfect. Noticed the zits on the 2nd print. I'm showing not much load on the rpi 3, load average 0.29, 0.23, 0.24... Camera feed is turned off. This rpi is not running the GUI and a dedicated octopi. Straight walls do not show zits or blobs. When it attempts a circle, it "steps" with a slight pause which is causing the zits. I will try a print without octopi.
