### ISSUE TITLE
The "Suppress M105" setting is not remembered

### ISSUE THREAD

**Issue by Cylindric** [foosel/OctoPrint#354] opened 2014-01-21 01:11 UTC
Ticking the "Suppress M105" option on the Terminal page does not seem to be remembered between sessions (e.g. page reloads). Is it possible to add this option to the user profile or a cookie?

**Comment by foosel** [comment] 2015-03-23 12:48
Duplicate of #225

**Closed by foosel** 2015-03-23 12:48 UTC
Labels: type:request
